-- GENERIERT aus den früheren JSON-Universen; ab jetzt die Datenquelle.
-- Lokal:  bun run db:seed:local
-- Remote: bun run db:seed:remote

-- Umgekehrte Fremdschlüssel-Reihenfolge, damit der Seed wiederholbar ist.
DELETE FROM plot_points;
DELETE FROM characters;
DELETE FROM arcs;
DELETE FROM seasons;
DELETE FROM works;
DELETE FROM sagas;
DELETE FROM universes;

-- Star Wars

INSERT INTO universes (slug, name, sort_order) VALUES
  ('star-wars', 'Star Wars', 0);

INSERT INTO sagas (universe_slug, id, name, tone, sort_order) VALUES
  ('star-wars', 'high-republic', 'High Republic Era', 'arc-1', 0),
  ('star-wars', 'prequel', 'Prequel-Ära', 'arc-2', 1),
  ('star-wars', 'fall-of-the-jedi', 'Fall of the Jedi', 'arc-3', 2),
  ('star-wars', 'original', 'Original-Trilogie', 'arc-1', 3),
  ('star-wars', 'new-republic', 'New Republic Era', 'arc-2', 4),
  ('star-wars', 'rise-of-the-first-order', 'Rise of the First Order', 'arc-3', 5);

INSERT INTO works (universe_slug, slug, title, short, kind, released, chronology, lore_date, saga_id, required, unit, range_start, range_end, now_playing, sort_order) VALUES
  ('star-wars', 'young-jedi-adventures', 'Star Wars: Young Jedi Adventures', 'Young Jedi Adventures', 'serie', '2023-05-04', 1, '200 BBY', 'high-republic', 0, 'Folge', 1, 10, NULL, 0),
  ('star-wars', 'the-acolyte', 'The Acolyte', 'The Acolyte', 'serie', '2024-06-04', 5, '132 BBY', 'high-republic', 0, 'Folge', 1, 8, NULL, 1),
  ('star-wars', 'episode-i', 'Episode I – Die dunkle Bedrohung', 'Episode I', 'film', '1999-05-19', 10, '32 BBY', 'prequel', 1, 'Min.', 0, 136, NULL, 2),
  ('star-wars', 'episode-ii', 'Episode II – Angriff der Klonkrieger', 'Episode II', 'film', '2002-05-16', 20, '22 BBY', 'prequel', 1, 'Min.', 0, 142, NULL, 3),
  ('star-wars', 'the-clone-wars', 'The Clone Wars', 'Clone Wars', 'serie', '2008-10-03', 25, '22–19 BBY', 'prequel', 0, 'Folge', 1, 22, NULL, 4),
  ('star-wars', 'episode-iii', 'Episode III – Die Rache der Sith', 'Episode III', 'film', '2005-05-19', 30, '19 BBY', 'prequel', 1, 'Min.', 0, 140, NULL, 5),
  ('star-wars', 'bad-batch', 'Star Wars: The Bad Batch', 'The Bad Batch', 'serie', '2021-05-04', 33, '19 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 16, NULL, 6),
  ('star-wars', 'tales-of-the-empire', 'Tales of the Empire', 'Tales of the Empire', 'serie', '2024-05-04', 36, '19–9 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 6, NULL, 7),
  ('star-wars', 'obi-wan-kenobi', 'Obi-Wan Kenobi', 'Obi-Wan Kenobi', 'serie', '2022-05-27', 38, '9 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 6, NULL, 8),
  ('star-wars', 'solo', 'Solo', 'Solo', 'film', '2018-05-24', 40, '13 BBY', 'fall-of-the-jedi', 0, 'Min.', 0, 135, NULL, 9),
  ('star-wars', 'star-wars-rebels', 'Star Wars Rebels', 'Star Wars Rebels', 'serie', '2014-10-03', 55, '5–0 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 15, NULL, 10),
  ('star-wars', 'andor', 'Andor', 'Andor', 'serie', '2022-09-21', 58, '5–1 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 12, NULL, 11),
  ('star-wars', 'rogue-one', 'Rogue One', 'Rogue One', 'film', '2016-12-15', 60, '0 BBY', 'fall-of-the-jedi', 0, 'Min.', 0, 133, NULL, 12),
  ('star-wars', 'tales-of-the-underworld', 'Tales of the Underworld', 'Tales of the Underworld', 'serie', '2025-05-04', 62, '0 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 6, NULL, 13),
  ('star-wars', 'episode-iv', 'Episode IV – Eine neue Hoffnung', 'Episode IV', 'film', '1977-05-25', 70, '0 BBY', 'original', 1, 'Min.', 0, 121, NULL, 14),
  ('star-wars', 'episode-v', 'Episode V – Das Imperium schlägt zurück', 'Episode V', 'film', '1980-05-21', 80, '3 ABY', 'original', 1, 'Min.', 0, 124, NULL, 15),
  ('star-wars', 'episode-vi', 'Episode VI – Die Rückkehr der Jedi-Ritter', 'Episode VI', 'film', '1983-05-25', 90, '4 ABY', 'original', 1, 'Min.', 0, 131, NULL, 16),
  ('star-wars', 'the-mandalorian', 'The Mandalorian – Staffel 1', 'The Mandalorian', 'serie', '2019-11-12', 100, '9 ABY', 'new-republic', 1, 'Folge', 1, 8, NULL, 17),
  ('star-wars', 'book-of-boba-fett', 'The Book of Boba Fett', 'Book of Boba Fett', 'serie', '2021-12-29', 104, '9 ABY', 'new-republic', 0, 'Folge', 1, 7, NULL, 18),
  ('star-wars', 'skeleton-crew', 'Star Wars: Skeleton Crew', 'Skeleton Crew', 'serie', '2024-12-02', 107, '3 ABY', 'new-republic', 0, 'Folge', 1, 8, NULL, 19),
  ('star-wars', 'ahsoka', 'Ahsoka', 'Ahsoka', 'serie', '2023-08-22', 110, '9 ABY', 'new-republic', 0, 'Folge', 1, 8, NULL, 20),
  ('star-wars', 'maul-shadow-lord', 'Maul: Shadow Lord', 'Maul: Shadow Lord', 'serie', '2026-04-06', 115, '9 ABY', 'new-republic', 0, 'Folge', 1, 8, NULL, 21),
  ('star-wars', 'mandalorian-und-grogu', 'The Mandalorian & Grogu', 'Mandalorian & Grogu', 'film', '2026-05-22', 120, '10 ABY', 'new-republic', 1, 'Min.', 0, 130, 1, 22),
  ('star-wars', 'star-wars-resistance', 'Star Wars Resistance', 'Star Wars Resistance', 'serie', '2018-10-07', 125, '28–29 ABY', 'rise-of-the-first-order', 0, 'Folge', 1, 21, NULL, 23),
  ('star-wars', 'episode-vii', 'Episode VII – Das Erwachen der Macht', 'Episode VII', 'film', '2015-12-17', 130, '34 ABY', 'rise-of-the-first-order', 1, 'Min.', 0, 138, NULL, 24),
  ('star-wars', 'episode-viii', 'Episode VIII – Die letzten Jedi', 'Episode VIII', 'film', '2017-12-14', 140, '34 ABY', 'rise-of-the-first-order', 1, 'Min.', 0, 152, NULL, 25),
  ('star-wars', 'episode-ix', 'Episode IX – Der Aufstieg Skywalkers', 'Episode IX', 'film', '2019-12-18', 150, '35 ABY', 'rise-of-the-first-order', 1, 'Min.', 0, 142, NULL, 26);

INSERT INTO arcs (universe_slug, id, work_slug, name, tone, sort_order) VALUES
  ('star-wars', 'yja-tempel', 'young-jedi-adventures', 'Der Tempel', 'arc-1', 0),
  ('star-wars', 'yja-freundschaft', 'young-jedi-adventures', 'Freundschaft', 'arc-2', 1),
  ('star-wars', 'acolyte-schwestern', 'the-acolyte', 'Die Schwestern', 'arc-1', 2),
  ('star-wars', 'acolyte-jedi', 'the-acolyte', 'Die Jedi', 'arc-2', 3),
  ('star-wars', 'acolyte-schatten', 'the-acolyte', 'Der Schatten', 'arc-3', 4),
  ('star-wars', 'iv-held', 'episode-iv', 'Heldenreise', 'arc-1', 5),
  ('star-wars', 'iv-rebellion', 'episode-iv', 'Rebellion', 'arc-2', 6),
  ('star-wars', 'iv-imperium', 'episode-iv', 'Imperium', 'arc-3', 7),
  ('star-wars', 'batch-batch', 'bad-batch', 'Die Überlebenden', 'arc-1', 8),
  ('star-wars', 'batch-rat', 'bad-batch', 'Der Rat der Macht', 'arc-2', 9),
  ('star-wars', 'batch-imperium', 'bad-batch', 'Das Imperium', 'arc-3', 10),
  ('star-wars', 'tote-inquisitorin', 'tales-of-the-empire', 'Die Inquisitorin', 'arc-1', 11),
  ('star-wars', 'tote-dathomir', 'tales-of-the-empire', 'Dathomir', 'arc-2', 12),
  ('star-wars', 'kenobi-obi-wan', 'obi-wan-kenobi', 'Der verlorene Meister', 'arc-1', 13),
  ('star-wars', 'kenobi-anakin', 'obi-wan-kenobi', 'Der gefallene Schüler', 'arc-2', 14),
  ('star-wars', 'kenobi-vader', 'obi-wan-kenobi', 'Die Konfrontation', 'arc-3', 15),
  ('star-wars', 'rebels-ghost', 'star-wars-rebels', 'Die Crew der Ghost', 'arc-1', 16),
  ('star-wars', 'rebels-erwachen', 'star-wars-rebels', 'Das Erwachen der Rebellion', 'arc-2', 17),
  ('star-wars', 'rebels-imperium', 'star-wars-rebels', 'Das Imperium', 'arc-3', 18),
  ('star-wars', 'andor-cassian', 'andor', 'Cassians Weg', 'arc-1', 19),
  ('star-wars', 'andor-rebellion', 'andor', 'Die Rebellion', 'arc-2', 20),
  ('star-wars', 'andor-imperium', 'andor', 'Das Imperium', 'arc-3', 21),
  ('star-wars', 'totu-unterwelt', 'tales-of-the-underworld', 'Die Unterwelt', 'arc-3', 22),
  ('star-wars', 'm-kind', 'the-mandalorian', 'Das Kind', 'arc-1', 23),
  ('star-wars', 'm-gilde', 'the-mandalorian', 'Die Gilde', 'arc-2', 24),
  ('star-wars', 'm-gideon', 'the-mandalorian', 'Moff Gideon', 'arc-3', 25),
  ('star-wars', 'boba-thron', 'book-of-boba-fett', 'Der Thron', 'arc-1', 26),
  ('star-wars', 'boba-vergangenheit', 'book-of-boba-fett', 'Die Vergangenheit', 'arc-2', 27),
  ('star-wars', 'boba-tatooine', 'book-of-boba-fett', 'Tatooine', 'arc-3', 28),
  ('star-wars', 'sc-kinder', 'skeleton-crew', 'Die Kinder', 'arc-1', 29),
  ('star-wars', 'sc-jod', 'skeleton-crew', 'Jod Na Nawood', 'arc-2', 30),
  ('star-wars', 'sc-galaxis', 'skeleton-crew', 'Die Galaxis', 'arc-3', 31),
  ('star-wars', 'ahsoka-ahsoka', 'ahsoka', 'Die Rückkehr der Jedi', 'arc-1', 32),
  ('star-wars', 'ahsoka-din-djarin', 'ahsoka', 'Die Bande des Großen Geheimnisses', 'arc-2', 33),
  ('star-wars', 'ahsoka-empire', 'ahsoka', 'Das neue Imperium', 'arc-3', 34),
  ('star-wars', 'maul-schatten', 'maul-shadow-lord', 'Der Schattenlord', 'arc-1', 35),
  ('star-wars', 'maul-rache', 'maul-shadow-lord', 'Rache', 'arc-3', 36),
  ('star-wars', 'resistance-kaz', 'star-wars-resistance', 'Kazuda Xiono', 'arc-1', 37),
  ('star-wars', 'resistance-erste-ordnung', 'star-wars-resistance', 'Die Erste Ordnung', 'arc-3', 38);

INSERT INTO characters (universe_slug, work_slug, id, name, initials, sort_order) VALUES
  ('star-wars', 'young-jedi-adventures', 'kai-brightstar', 'Kai Brightstar', 'KB', 0),
  ('star-wars', 'young-jedi-adventures', 'lys-solay', 'Lys Solay', 'LS', 1),
  ('star-wars', 'young-jedi-adventures', 'nubs', 'Nubs', 'NU', 2),
  ('star-wars', 'the-acolyte', 'osha', 'Osha Aniseya', 'OA', 3),
  ('star-wars', 'the-acolyte', 'mae', 'Mae Aniseya', 'MA', 4),
  ('star-wars', 'the-acolyte', 'sol', 'Meister Sol', 'MS', 5),
  ('star-wars', 'the-acolyte', 'qimir', 'Qimir', 'QI', 6),
  ('star-wars', 'episode-iv', 'luke', 'Luke Skywalker', 'LS', 7),
  ('star-wars', 'episode-iv', 'leia', 'Leia Organa', 'LO', 8),
  ('star-wars', 'episode-iv', 'han', 'Han Solo', 'HS', 9),
  ('star-wars', 'episode-iv', 'vader', 'Darth Vader', 'DV', 10),
  ('star-wars', 'episode-iv', 'obi-wan', 'Obi-Wan Kenobi', 'OK', 11),
  ('star-wars', 'episode-iv', 'r2-d2', 'R2-D2', 'R2', 12),
  ('star-wars', 'episode-iv', 'c-3po', 'C-3PO', '3PO', 13),
  ('star-wars', 'episode-iv', 'tarkin', 'Grand Moff Tarkin', 'GT', 14),
  ('star-wars', 'episode-iv', 'chewbacca', 'Chewbacca', 'CH', 15),
  ('star-wars', 'bad-batch', 'hunter', 'Hunter', 'HU', 16),
  ('star-wars', 'bad-batch', 'omega', 'Omega', 'OM', 17),
  ('star-wars', 'bad-batch', 'crosshair', 'Crosshair', 'CH', 18),
  ('star-wars', 'bad-batch', 'nala-se', 'Nala Se', 'NS', 19),
  ('star-wars', 'tales-of-the-empire', 'morgan-elsbeth', 'Morgan Elsbeth', 'ME', 20),
  ('star-wars', 'tales-of-the-empire', 'barriss', 'Barriss Offee', 'BO', 21),
  ('star-wars', 'obi-wan-kenobi', 'obi-wan', 'Obi-Wan Kenobi', 'OK', 22),
  ('star-wars', 'obi-wan-kenobi', 'leia-organa', 'Leia Organa', 'LO', 23),
  ('star-wars', 'obi-wan-kenobi', 'vader', 'Darth Vader', 'DV', 24),
  ('star-wars', 'obi-wan-kenobi', 'reva', 'Reva Sevander', 'RS', 25),
  ('star-wars', 'star-wars-rebels', 'ezra', 'Ezra Bridger', 'EB', 26),
  ('star-wars', 'star-wars-rebels', 'kanan', 'Kanan Jarrus', 'KJ', 27),
  ('star-wars', 'star-wars-rebels', 'hera', 'Hera Syndulla', 'HS', 28),
  ('star-wars', 'star-wars-rebels', 'thrawn', 'Großadmiral Thrawn', 'GT', 29),
  ('star-wars', 'andor', 'cassian', 'Cassian Andor', 'CA', 30),
  ('star-wars', 'andor', 'mon-mothma', 'Mon Mothma', 'MM', 31),
  ('star-wars', 'andor', 'bix', 'Bix Caleen', 'BC', 32),
  ('star-wars', 'andor', 'syril', 'Syril Karn', 'SK', 33),
  ('star-wars', 'tales-of-the-underworld', 'ventress', 'Asajj Ventress', 'AV', 34),
  ('star-wars', 'tales-of-the-underworld', 'boba', 'Boba Fett', 'BF', 35),
  ('star-wars', 'the-mandalorian', 'din', 'Din Djarin', 'DD', 36),
  ('star-wars', 'the-mandalorian', 'grogu', 'Grogu', 'GR', 37),
  ('star-wars', 'the-mandalorian', 'greef', 'Greef Karga', 'GK', 38),
  ('star-wars', 'the-mandalorian', 'cara', 'Cara Dune', 'CD', 39),
  ('star-wars', 'the-mandalorian', 'gideon', 'Moff Gideon', 'MG', 40),
  ('star-wars', 'the-mandalorian', 'ig-11', 'IG-11', 'IG', 41),
  ('star-wars', 'the-mandalorian', 'kuiil', 'Kuiil', 'KU', 42),
  ('star-wars', 'book-of-boba-fett', 'boba', 'Boba Fett', 'BF', 43),
  ('star-wars', 'book-of-boba-fett', 'fennec', 'Fennec Shand', 'FS', 44),
  ('star-wars', 'book-of-boba-fett', 'din', 'Din Djarin', 'DD', 45),
  ('star-wars', 'book-of-boba-fett', 'cad-bane', 'Cad Bane', 'CB', 46),
  ('star-wars', 'skeleton-crew', 'wim', 'Wim', 'WI', 47),
  ('star-wars', 'skeleton-crew', 'fern', 'Fern', 'FE', 48),
  ('star-wars', 'skeleton-crew', 'jod', 'Jod Na Nawood', 'JN', 49),
  ('star-wars', 'skeleton-crew', 'sm-33', 'SM-33', 'SM', 50),
  ('star-wars', 'ahsoka', 'ahsoka-tano', 'Ahsoka Tano', 'AT', 51),
  ('star-wars', 'ahsoka', 'sabine', 'Sabine Wren', 'SW', 52),
  ('star-wars', 'ahsoka', 'din-ahsoka', 'Din Djarin', 'DD', 53),
  ('star-wars', 'ahsoka', 'thrawn-ahsoka', 'Großadmiral Thrawn', 'GT', 54),
  ('star-wars', 'maul-shadow-lord', 'maul', 'Darth Maul', 'DM', 55),
  ('star-wars', 'maul-shadow-lord', 'ochi', 'Ochi von Bestoon', 'OB', 56),
  ('star-wars', 'star-wars-resistance', 'kaz', 'Kazuda Xiono', 'KX', 57),
  ('star-wars', 'star-wars-resistance', 'poe', 'Poe Dameron', 'PD', 58),
  ('star-wars', 'star-wars-resistance', 'torra', 'Torra Doza', 'TD', 59);

INSERT INTO plot_points (universe_slug, id, work_slug, character_id, arc_id, at, text) VALUES
  ('star-wars', 'yja-0', 'young-jedi-adventures', 'kai-brightstar', 'yja-tempel', 1, 'Beginnt seine Ausbildung im Jedi-Tempel des Hochrepublik-Zeitalters.'),
  ('star-wars', 'yja-1', 'young-jedi-adventures', 'kai-brightstar', 'yja-freundschaft', 5, 'Lernt, dass wahre Jedi-Stärke aus Zusammenhalt statt Alleingang kommt.'),
  ('star-wars', 'yja-2', 'young-jedi-adventures', 'lys-solay', 'yja-freundschaft', 3, 'Hilft einem verängstigten Wesen, sich der Gruppe anzuschließen.'),
  ('star-wars', 'yja-3', 'young-jedi-adventures', 'nubs', 'yja-tempel', 2, 'Sorgt trotz fehlender Worte für den Zusammenhalt der jungen Padawane.'),
  ('star-wars', 'acolyte-0', 'the-acolyte', 'mae', 'acolyte-schwestern', 1, 'Beginnt eine Mordserie an den Jedi, die einst ihr Zuhause zerstörten.'),
  ('star-wars', 'acolyte-1', 'the-acolyte', 'osha', 'acolyte-schwestern', 3, 'Wird fälschlich der Verbrechen ihrer verschollen geglaubten Zwillingsschwester verdächtigt.'),
  ('star-wars', 'acolyte-2', 'the-acolyte', 'sol', 'acolyte-jedi', 6, 'Gesteht Osha, was auf Brendok wirklich geschah.'),
  ('star-wars', 'acolyte-3', 'the-acolyte', 'qimir', 'acolyte-schatten', 7, 'Enttarnt sich als heimlicher Sith-Lehrer im Hintergrund.'),
  ('star-wars', 'acolyte-4', 'the-acolyte', 'osha', 'acolyte-schatten', 8, 'Wendet sich nach dem Verlust ihrer Schwester der dunklen Seite zu.'),
  ('star-wars', 'episode-iv-0', 'episode-iv', 'luke', 'iv-held', 18, 'Findet Leias Hilferuf im Speicher von R2-D2.'),
  ('star-wars', 'episode-iv-1', 'episode-iv', 'luke', 'iv-held', 35, 'Verliert sein Zuhause und schließt sich Obi-Wan an.'),
  ('star-wars', 'episode-iv-2', 'episode-iv', 'luke', 'iv-rebellion', 48, 'Sucht mit Obi-Wan in Mos Eisley einen Piloten.'),
  ('star-wars', 'episode-iv-3', 'episode-iv', 'luke', 'iv-imperium', 75, 'Befreit Leia aus dem Zellenblock des Todessterns.'),
  ('star-wars', 'episode-iv-4', 'episode-iv', 'luke', 'iv-rebellion', 112, 'Fliegt den entscheidenden Angriff auf den Todesstern.'),
  ('star-wars', 'episode-iv-5', 'episode-iv', 'leia', 'iv-rebellion', 2, 'Versteckt die gestohlenen Pläne in R2-D2.'),
  ('star-wars', 'episode-iv-6', 'episode-iv', 'leia', 'iv-imperium', 40, 'Hält im Verhör stand – trotz Drohung gegen Alderaan.'),
  ('star-wars', 'episode-iv-7', 'episode-iv', 'leia', 'iv-held', 78, 'Übernimmt bei der eigenen Rettung das Kommando.'),
  ('star-wars', 'episode-iv-8', 'episode-iv', 'leia', 'iv-rebellion', 118, 'Ehrt die Helden nach der Schlacht von Yavin.'),
  ('star-wars', 'episode-iv-9', 'episode-iv', 'han', 'iv-rebellion', 50, 'Nimmt den Flug nach Alderaan gegen hohen Lohn an.'),
  ('star-wars', 'episode-iv-10', 'episode-iv', 'han', 'iv-imperium', 55, 'Entkommt mit dem Falken der imperialen Blockade.'),
  ('star-wars', 'episode-iv-11', 'episode-iv', 'han', 'iv-held', 108, 'Kehrt im letzten Moment zur Schlacht zurück.'),
  ('star-wars', 'episode-iv-12', 'episode-iv', 'vader', 'iv-imperium', 4, 'Entert das Rebellenschiff und sucht die Pläne.'),
  ('star-wars', 'episode-iv-13', 'episode-iv', 'vader', 'iv-held', 88, 'Trifft seinen alten Meister wieder.'),
  ('star-wars', 'episode-iv-14', 'episode-iv', 'vader', 'iv-imperium', 110, 'Verfolgt die Angreifer im Graben persönlich.'),
  ('star-wars', 'episode-iv-15', 'episode-iv', 'obi-wan', 'iv-held', 30, 'Erzählt Luke von dessen Vater und dem Lichtschwert.'),
  ('star-wars', 'episode-iv-16', 'episode-iv', 'obi-wan', 'iv-rebellion', 60, 'Schaltet den Traktorstrahl des Todessterns ab.'),
  ('star-wars', 'episode-iv-17', 'episode-iv', 'obi-wan', 'iv-held', 88, 'Stellt sich Vader im Duell.'),
  ('star-wars', 'episode-iv-18', 'episode-iv', 'r2-d2', 'iv-rebellion', 8, 'Flieht mit den Plänen auf den Wüstenplaneten.'),
  ('star-wars', 'episode-iv-19', 'episode-iv', 'r2-d2', 'iv-held', 22, 'Macht sich allein auf die Suche nach Obi-Wan.'),
  ('star-wars', 'episode-iv-20', 'episode-iv', 'r2-d2', 'iv-rebellion', 105, 'Fliegt als Astromech hinter Luke in die Schlacht.'),
  ('star-wars', 'episode-iv-21', 'episode-iv', 'c-3po', 'iv-rebellion', 10, 'Landet mit R2-D2 in einer Rettungskapsel auf Tatooine.'),
  ('star-wars', 'episode-iv-22', 'episode-iv', 'c-3po', 'iv-imperium', 80, 'Hält im Kontrollraum die Stellung.'),
  ('star-wars', 'episode-iv-23', 'episode-iv', 'tarkin', 'iv-imperium', 38, 'Demonstriert die Macht der Station an Alderaan.'),
  ('star-wars', 'episode-iv-24', 'episode-iv', 'tarkin', 'iv-imperium', 114, 'Lehnt die Evakuierung der Station ab.'),
  ('star-wars', 'episode-iv-25', 'episode-iv', 'chewbacca', 'iv-rebellion', 50, 'Fliegt mit Han den Millennium Falken.'),
  ('star-wars', 'episode-iv-26', 'episode-iv', 'chewbacca', 'iv-imperium', 70, 'Spielt den Gefangenen, um in den Zellenblock zu kommen.'),
  ('star-wars', 'batch-0', 'bad-batch', 'hunter', 'batch-batch', 1, 'Übernimmt nach Order 66 das Kommando über die desorientierte Truppe.'),
  ('star-wars', 'batch-1', 'bad-batch', 'hunter', 'batch-imperium', 3, 'Lehnt die Umrüstung auf Kontroll-Chips ab und flieht mit dem Team.'),
  ('star-wars', 'batch-2', 'bad-batch', 'omega', 'batch-batch', 1, 'Schließt sich der Truppe als heimliches Klon-Mädchen an.'),
  ('star-wars', 'batch-3', 'bad-batch', 'omega', 'batch-rat', 8, 'Wird von Nala Se als genetisch besonders wertvoll identifiziert.'),
  ('star-wars', 'batch-4', 'bad-batch', 'crosshair', 'batch-imperium', 1, 'Bleibt dem Imperium treu und wird zum Gegenspieler seines eigenen Teams.'),
  ('star-wars', 'batch-5', 'bad-batch', 'crosshair', 'batch-imperium', 16, 'Bricht endgültig mit dem Imperium, nachdem er selbst zur Wegwerfware wird.'),
  ('star-wars', 'batch-6', 'bad-batch', 'nala-se', 'batch-rat', 3, 'Versucht, die Klonforschung vor imperialem Zugriff zu schützen.'),
  ('star-wars', 'tote-0', 'tales-of-the-empire', 'morgan-elsbeth', 'tote-inquisitorin', 1, 'Verliert ihre Heimat Dathomir an die Klonkriege und schwört Rache.'),
  ('star-wars', 'tote-1', 'tales-of-the-empire', 'morgan-elsbeth', 'tote-inquisitorin', 3, 'Steigt zur Handlangerin Thrawns und zur Magistratin von Corvus auf.'),
  ('star-wars', 'tote-2', 'tales-of-the-empire', 'barriss', 'tote-dathomir', 4, 'Verlässt nach ihrem Verrat den Jedi-Orden und sucht in der Dunkelheit neuen Sinn.'),
  ('star-wars', 'kenobi-0', 'obi-wan-kenobi', 'obi-wan', 'kenobi-obi-wan', 1, 'Lebt zurückgezogen auf Tatooine und wacht heimlich über den jungen Luke.'),
  ('star-wars', 'kenobi-1', 'obi-wan-kenobi', 'obi-wan', 'kenobi-obi-wan', 2, 'Reist nach Daiyu, um die entführte Leia zu retten.'),
  ('star-wars', 'kenobi-2', 'obi-wan-kenobi', 'obi-wan', 'kenobi-vader', 4, 'Stellt sich Vader zum ersten Mal seit Mustafar in einem verheerenden Duell.'),
  ('star-wars', 'kenobi-3', 'obi-wan-kenobi', 'obi-wan', 'kenobi-anakin', 6, 'Erkennt, dass in Vader nichts vom einstigen Anakin übrig ist – und lässt los.'),
  ('star-wars', 'kenobi-4', 'obi-wan-kenobi', 'leia-organa', 'kenobi-obi-wan', 1, 'Wird von Kopfgeldjägern der Dritten Schwester entführt.'),
  ('star-wars', 'kenobi-5', 'obi-wan-kenobi', 'leia-organa', 'kenobi-obi-wan', 3, 'Beginnt, dem widerwilligen Obi-Wan zu vertrauen.'),
  ('star-wars', 'kenobi-6', 'obi-wan-kenobi', 'vader', 'kenobi-anakin', 3, 'Lässt Reva wissen, dass er von Obi-Wans Überleben erfahren hat.'),
  ('star-wars', 'kenobi-7', 'obi-wan-kenobi', 'vader', 'kenobi-vader', 4, 'Setzt ein Dorf in Brand, um Obi-Wan aus der Deckung zu locken.'),
  ('star-wars', 'kenobi-8', 'obi-wan-kenobi', 'reva', 'kenobi-vader', 5, 'Enthüllt ihre wahre Absicht: Rache an Vader statt Loyalität.'),
  ('star-wars', 'kenobi-9', 'obi-wan-kenobi', 'reva', 'kenobi-vader', 6, 'Verschont den jungen Luke auf Tatooine und lässt von der Rache ab.'),
  ('star-wars', 'rebels-0', 'star-wars-rebels', 'ezra', 'rebels-ghost', 1, 'Wird von der Crew der Ghost aus dem Leben als Straßendieb auf Lothal geholt.'),
  ('star-wars', 'rebels-1', 'star-wars-rebels', 'ezra', 'rebels-erwachen', 15, 'Opfert sich, um Thrawn ins unbekannte Weltall zu verbannen.'),
  ('star-wars', 'rebels-2', 'star-wars-rebels', 'kanan', 'rebels-ghost', 1, 'Bildet Ezra heimlich als Jedi aus, ohne Orden oder Tempel.'),
  ('star-wars', 'rebels-3', 'star-wars-rebels', 'kanan', 'rebels-imperium', 12, 'Verliert im Kampf gegen die Inquisitoren sein Augenlicht.'),
  ('star-wars', 'rebels-4', 'star-wars-rebels', 'hera', 'rebels-erwachen', 5, 'Vereint verstreute Widerstandszellen zur organisierten Rebellion.'),
  ('star-wars', 'rebels-5', 'star-wars-rebels', 'thrawn', 'rebels-imperium', 10, 'Analysiert die Kunst und Taktik der Rebellen, um sie gezielt zu zerschlagen.'),
  ('star-wars', 'andor-0', 'andor', 'cassian', 'andor-cassian', 1, 'Sucht auf Ferrix Antworten zum Verschwinden seiner Schwester – und tötet zwei Corp-Wachen in Notwehr.'),
  ('star-wars', 'andor-1', 'andor', 'cassian', 'andor-rebellion', 3, 'Wird von Luthen Rael angeworben, nachdem er der ISB nur knapp entkommt.'),
  ('star-wars', 'andor-2', 'andor', 'cassian', 'andor-imperium', 8, 'Wird ohne fairen Prozess zu sechs Jahren Zwangsarbeit auf Narkina 5 verurteilt.'),
  ('star-wars', 'andor-3', 'andor', 'cassian', 'andor-rebellion', 10, 'Organisiert den Ausbruch aus dem Gefängniskomplex.'),
  ('star-wars', 'andor-4', 'andor', 'cassian', 'andor-cassian', 12, 'Kehrt nach Ferrix zurück und übernimmt bei Maarvas Beerdigung offen die Rolle des Rebellen.'),
  ('star-wars', 'andor-5', 'andor', 'mon-mothma', 'andor-rebellion', 4, 'Schleust unter dem Deckmantel der Wohltätigkeit Gelder zur Finanzierung der Rebellion.'),
  ('star-wars', 'andor-6', 'andor', 'mon-mothma', 'andor-imperium', 9, 'Manövriert sich im Senat gegen wachsendes Misstrauen ihres Umfelds und der ISB.'),
  ('star-wars', 'andor-7', 'andor', 'bix', 'andor-cassian', 2, 'Verschafft Cassian einen riskanten Deal mit einem Schmuggler.'),
  ('star-wars', 'andor-8', 'andor', 'bix', 'andor-imperium', 11, 'Wird von der ISB verhört und schwer gefoltert.'),
  ('star-wars', 'andor-9', 'andor', 'syril', 'andor-imperium', 1, 'Verfolgt eigenmächtig die Ermittlungen zum Doppelmord auf Ferrix, gegen den Willen seiner Vorgesetzten.'),
  ('star-wars', 'andor-10', 'andor', 'syril', 'andor-imperium', 9, 'Wird von der ISB rekrutiert, um Cassian auf Chandrila aufzuspüren.'),
  ('star-wars', 'totu-0', 'tales-of-the-underworld', 'ventress', 'totu-unterwelt', 1, 'Arbeitet als Kopfgeldjägerin an der Seite von Boba Fett auf einem riskanten Auftrag.'),
  ('star-wars', 'totu-1', 'tales-of-the-underworld', 'boba', 'totu-unterwelt', 3, 'Bekräftigt vor Ventress seinen Ruf als gnadenloser Kopfgeldjäger.'),
  ('star-wars', 'the-mandalorian-0', 'the-mandalorian', 'din', 'm-gilde', 1, 'Nimmt einen ungewöhnlichen Auftrag des Klienten an.'),
  ('star-wars', 'the-mandalorian-1', 'the-mandalorian', 'din', 'm-kind', 1, 'Findet sein Ziel – und es ist ein Kind.'),
  ('star-wars', 'the-mandalorian-2', 'the-mandalorian', 'din', 'm-gilde', 3, 'Liefert ab, bereut es und holt das Kind zurück.'),
  ('star-wars', 'the-mandalorian-3', 'the-mandalorian', 'din', 'm-kind', 4, 'Sucht auf Sorgan ein Versteck für das Kind.'),
  ('star-wars', 'the-mandalorian-4', 'the-mandalorian', 'din', 'm-gideon', 7, 'Kehrt nach Nevarro zurück, um den Klienten zu stellen.'),
  ('star-wars', 'the-mandalorian-5', 'the-mandalorian', 'din', 'm-kind', 8, 'Nimmt den Auftrag an, das Kind zu seinesgleichen zu bringen.'),
  ('star-wars', 'the-mandalorian-6', 'the-mandalorian', 'grogu', 'm-kind', 1, 'Wird im Lager der Nikto entdeckt.'),
  ('star-wars', 'the-mandalorian-7', 'the-mandalorian', 'grogu', 'm-kind', 2, 'Hebt mit der Macht einen Mudhorn an.'),
  ('star-wars', 'the-mandalorian-8', 'the-mandalorian', 'grogu', 'm-gideon', 7, 'Wird von Sturmtruppen entführt.'),
  ('star-wars', 'the-mandalorian-9', 'the-mandalorian', 'greef', 'm-gilde', 1, 'Vermittelt Din den Auftrag.'),
  ('star-wars', 'the-mandalorian-10', 'the-mandalorian', 'greef', 'm-gilde', 3, 'Führt die Gilde gegen Din an.'),
  ('star-wars', 'the-mandalorian-11', 'the-mandalorian', 'greef', 'm-gideon', 7, 'Bietet Din einen Deal an – mit Hintergedanken.'),
  ('star-wars', 'the-mandalorian-12', 'the-mandalorian', 'cara', 'm-kind', 4, 'Trifft Din auf Sorgan im Zweikampf.'),
  ('star-wars', 'the-mandalorian-13', 'the-mandalorian', 'cara', 'm-gideon', 7, 'Schließt sich dem Plan für Nevarro an.'),
  ('star-wars', 'the-mandalorian-14', 'the-mandalorian', 'gideon', 'm-gideon', 7, 'Umstellt die Cantina auf Nevarro.'),
  ('star-wars', 'the-mandalorian-15', 'the-mandalorian', 'gideon', 'm-gideon', 8, 'Taucht mit dem Dunkelschwert auf.'),
  ('star-wars', 'the-mandalorian-16', 'the-mandalorian', 'ig-11', 'm-gilde', 1, 'Wetteifert mit Din um dasselbe Ziel.'),
  ('star-wars', 'the-mandalorian-17', 'the-mandalorian', 'ig-11', 'm-kind', 8, 'Beschützt das Kind – umprogrammiert.'),
  ('star-wars', 'the-mandalorian-18', 'the-mandalorian', 'kuiil', 'm-kind', 1, 'Hilft Din, das Lager zu erreichen.'),
  ('star-wars', 'the-mandalorian-19', 'the-mandalorian', 'kuiil', 'm-kind', 2, 'Repariert das zerlegte Schiff.'),
  ('star-wars', 'the-mandalorian-20', 'the-mandalorian', 'kuiil', 'm-kind', 7, 'Bringt das Kind in Sicherheit.'),
  ('star-wars', 'boba-0', 'book-of-boba-fett', 'boba', 'boba-vergangenheit', 2, 'Wird von Tuskenräubern gefangen genommen und lernt ihre Lebensweise.'),
  ('star-wars', 'boba-1', 'book-of-boba-fett', 'boba', 'boba-thron', 1, 'Übernimmt Jabbas altes Territorium auf Tatooine.'),
  ('star-wars', 'boba-2', 'book-of-boba-fett', 'boba', 'boba-thron', 5, 'Muss sich gegen die Übernahmeversuche des Pyke-Syndikats behaupten.'),
  ('star-wars', 'boba-3', 'book-of-boba-fett', 'fennec', 'boba-thron', 1, 'Wird Bobas rechte Hand und Sicherheitschefin.'),
  ('star-wars', 'boba-4', 'book-of-boba-fett', 'fennec', 'boba-thron', 5, 'Verhandelt mit den Straßenbanden von Mos Espa um Unterstützung.'),
  ('star-wars', 'boba-5', 'book-of-boba-fett', 'din', 'boba-tatooine', 6, 'Hilft Boba im entscheidenden Kampf gegen die Pykes.'),
  ('star-wars', 'boba-6', 'book-of-boba-fett', 'cad-bane', 'boba-thron', 6, 'Fordert Boba im Duell heraus, im Auftrag der Pykes.'),
  ('star-wars', 'sc-0', 'skeleton-crew', 'wim', 'sc-kinder', 1, 'Findet mit Freunden ein vergrabenes altes Schiff und startet versehentlich in den Hyperraum.'),
  ('star-wars', 'sc-1', 'skeleton-crew', 'wim', 'sc-galaxis', 8, 'Kehrt mit neuem Blick auf seine ruhige Heimatwelt zurück.'),
  ('star-wars', 'sc-2', 'skeleton-crew', 'fern', 'sc-kinder', 2, 'Übernimmt in der Gruppe die Führungsrolle, als Erwachsene fehlen.'),
  ('star-wars', 'sc-3', 'skeleton-crew', 'jod', 'sc-jod', 3, 'Gibt sich den Kindern gegenüber als Jedi aus, um ihr Vertrauen zu gewinnen.'),
  ('star-wars', 'sc-4', 'skeleton-crew', 'jod', 'sc-jod', 7, 'Wird als Pirat und Betrüger entlarvt.'),
  ('star-wars', 'sc-5', 'skeleton-crew', 'sm-33', 'sc-galaxis', 1, 'Erkennt die Kinder fälschlich als seine ''Captains'' an.'),
  ('star-wars', 'ahsoka-0', 'ahsoka', 'ahsoka-tano', 'ahsoka-ahsoka', 1, 'Folgt einer alten Karte, die zum verschollenen Großadmiral Thrawn führen soll.'),
  ('star-wars', 'ahsoka-1', 'ahsoka', 'ahsoka-tano', 'ahsoka-empire', 7, 'Stellt sich Thrawn im fernen Weltall zum entscheidenden Duell.'),
  ('star-wars', 'ahsoka-2', 'ahsoka', 'sabine', 'ahsoka-ahsoka', 2, 'Wird von Ahsoka in den Wegen der Macht unterrichtet, gegen deren eigene Zweifel.'),
  ('star-wars', 'ahsoka-3', 'ahsoka', 'sabine', 'ahsoka-din-djarin', 5, 'Reist eigenmächtig ins Unbekannte Weltall, um Ezra zu retten.'),
  ('star-wars', 'ahsoka-4', 'ahsoka', 'din-ahsoka', 'ahsoka-din-djarin', 4, 'Verrät Ahsoka Sabines Aufenthaltsort – aus Verpflichtung, nicht Überzeugung.'),
  ('star-wars', 'ahsoka-5', 'ahsoka', 'thrawn-ahsoka', 'ahsoka-empire', 7, 'Kehrt mit einer neuen Flotte aus dem Exil zurück.'),
  ('star-wars', 'maul-0', 'maul-shadow-lord', 'maul', 'maul-schatten', 1, 'Baut im Verborgenen ein neues Verbrechensnetzwerk nach dem Fall seines alten Syndikats auf.'),
  ('star-wars', 'maul-1', 'maul-shadow-lord', 'maul', 'maul-rache', 5, 'Verfolgt weiter seine Obsession, die Skywalker-Blutlinie auszulöschen.'),
  ('star-wars', 'maul-2', 'maul-shadow-lord', 'ochi', 'maul-schatten', 3, 'Bietet Maul seine Dienste als Assassine an.'),
  ('star-wars', 'resistance-0', 'star-wars-resistance', 'kaz', 'resistance-kaz', 1, 'Wird als verdeckter Spion des Widerstands auf die Ölplattform Colossus geschickt.'),
  ('star-wars', 'resistance-1', 'star-wars-resistance', 'poe', 'resistance-kaz', 1, 'Rekrutiert Kaz für die geheime Aufklärungsmission gegen die Erste Ordnung.'),
  ('star-wars', 'resistance-2', 'star-wars-resistance', 'torra', 'resistance-erste-ordnung', 18, 'Verteidigt Colossus gegen den offenen Angriff der Ersten Ordnung.'),
  ('star-wars', 'resistance-3', 'star-wars-resistance', 'kaz', 'resistance-erste-ordnung', 21, 'Schließt sich offen dem Widerstand gegen die Erste Ordnung an.');

-- Fate

INSERT INTO universes (slug, name, sort_order) VALUES
  ('fate', 'Fate', 1);

INSERT INTO sagas (universe_slug, id, name, tone, sort_order) VALUES
  ('fate', 'saga-stay-night', 'Fate/stay night Routen-Ära', 'arc-1', 0),
  ('fate', 'saga-zero', 'Vierter Heiliger Gralkrieg (Fate/Zero)', 'arc-2', 1),
  ('fate', 'saga-prototype', 'Fate/Prototype Universum', 'neutral', 2),
  ('fate', 'saga-kaleid-parallel', 'Kaleid-Parallelwelt (Prisma Illya)', 'arc-1', 3),
  ('fate', 'saga-apocrypha', 'Großer Gralkrieg (Apocrypha)', 'neutral', 4),
  ('fate', 'saga-grand-order-babylonia', 'Grand Order: Singularitäten', 'arc-3', 5),
  ('fate', 'saga-grand-order-lostbelt', 'Grand Order / Cosmos in the Lostbelt', 'arc-3', 6),
  ('fate', 'saga-fifth-war', 'Nach dem fünften Gralkrieg', 'neutral', 7);

INSERT INTO works (universe_slug, slug, title, short, kind, released, chronology, lore_date, saga_id, required, unit, range_start, range_end, now_playing, sort_order) VALUES
  ('fate', 'fate-stay-night-2006', 'Fate/stay night', 'stay night', 'serie', '2006-01-07', 30, '2004', 'saga-stay-night', 1, 'Folge', 1, 24, NULL, 0),
  ('fate', 'fate-zero', 'Fate/Zero', 'Zero', 'serie', '2011-10-01', 20, '1994', 'saga-zero', 1, 'Folge', 1, 25, NULL, 1),
  ('fate', 'fate-prototype', 'Fate/Prototype', 'Prototype', 'film', '2011-12-31', 10, '2003', 'saga-prototype', 0, 'Min.', 0, 12, NULL, 2),
  ('fate', 'fate-kaleid-liner-prisma-illya', 'Fate/kaleid liner PRISMA☆ILLYA', 'Prisma Illya', 'serie', '2013-07-13', 90, '2014', 'saga-kaleid-parallel', 1, 'Folge', 1, 10, NULL, 3),
  ('fate', 'fate-stay-night-unlimited-blade-works', 'Fate/stay night: Unlimited Blade Works', 'UBW', 'serie', '2014-10-04', 40, '2004', 'saga-stay-night', 1, 'Folge', 1, 25, NULL, 4),
  ('fate', 'fate-apocrypha', 'Fate/Apocrypha', 'Apocrypha', 'serie', '2017-07-02', 110, '2015', 'saga-apocrypha', 1, 'Folge', 1, 25, NULL, 5),
  ('fate', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'Fate/kaleid liner PRISMA ILLYA: Oath Under Snow', 'Prisma Movie 1', 'film', '2017-08-26', 100, '2015', 'saga-kaleid-parallel', 0, 'Min.', 0, 90, NULL, 6),
  ('fate', 'fate-heavens-feel-1-presage-flower', 'Fate/stay night: Heaven''s Feel I. presage flower', 'Heaven''s Feel I', 'film', '2017-10-14', 50, '2004', 'saga-stay-night', 1, 'Min.', 0, 120, NULL, 7),
  ('fate', 'fate-grand-order-moonlight-lostroom', 'Fate/Grand Order -MOONLIGHT/LOSTROOM-', 'Lostroom OVA', 'film', '2017-12-31', 120, '2016', 'saga-grand-order-lostbelt', 1, 'Min.', 0, 32, NULL, 8),
  ('fate', 'todays-menu-for-the-emiya-family', 'Today''s Menu for the Emiya Family', 'Emiya Gohan', 'serie', '2018-01-25', 80, '2005', 'saga-fifth-war', 0, 'Folge', 1, 13, NULL, 9),
  ('fate', 'fate-heavens-feel-2-lost-butterfly', 'Fate/stay night: Heaven''s Feel II. lost butterfly', 'Heaven''s Feel II', 'film', '2019-01-12', 60, '2004', 'saga-stay-night', 1, 'Min.', 0, 117, NULL, 10),
  ('fate', 'fate-grand-order-babylonia', 'Fate/Grand Order -Absolute Demonic Front: Babylonia-', 'Babylonia', 'serie', '2019-10-05', 140, '2016', 'saga-grand-order-babylonia', 1, 'Folge', 1, 21, NULL, 11),
  ('fate', 'fate-heavens-feel-3-spring-song', 'Fate/stay night: Heaven''s Feel III. spring song', 'Heaven''s Feel III', 'film', '2020-08-15', 70, '2004', 'saga-stay-night', 1, 'Min.', 0, 122, NULL, 12),
  ('fate', 'fate-grand-order-camelot', 'Fate/Grand Order THE MOVIE: Divine Realm of the Round Table -Camelot- Wandering; Agateram', 'Camelot', 'film', '2020-12-05', 130, '2016', 'saga-grand-order-babylonia', 0, 'Min.', 0, 89, NULL, 13);

INSERT INTO arcs (universe_slug, id, work_slug, name, tone, sort_order) VALUES
  ('fate', 'stay-night-fate-route', 'fate-stay-night-2006', 'Der Fate-Pfad: Shirous erster Gralkrieg', 'arc-1', 0),
  ('fate', 'zero-fourth-war', 'fate-zero', 'Der Vierte Heilige Gralkrieg', 'arc-2', 1),
  ('fate', 'proto-tokyo-1991', 'fate-prototype', 'Erster Tokio Gralkrieg (1991)', 'neutral', 2),
  ('fate', 'prisma-illya-transformation', 'fate-kaleid-liner-prisma-illya', 'Illyas Verwandlung zur Kaleidscope-Kriegerin', 'arc-1', 3),
  ('fate', 'ubw-route', 'fate-stay-night-unlimited-blade-works', 'Der UBW-Pfad: Rins Route und Archer', 'arc-1', 4),
  ('fate', 'apocrypha-great-war', 'fate-apocrypha', 'Schwarze und Rote Fraktion im Großen Gralkrieg', 'neutral', 5),
  ('fate', 'prisma-oath-shirou', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'Shirous Gralkrieg in der sterbenden Welt', 'arc-1', 6),
  ('fate', 'hf-1-shadow', 'fate-heavens-feel-1-presage-flower', 'Sakuras Schatten erwacht', 'arc-1', 7),
  ('fate', 'fgo-lostbelt-prologue', 'fate-grand-order-moonlight-lostroom', 'Schatten der ausgelöschten Zukunft', 'arc-3', 8),
  ('fate', 'gohan-alltag', 'todays-menu-for-the-emiya-family', 'Emiya-Haushalt Kochalltag', 'neutral', 9),
  ('fate', 'hf-2-corruption', 'fate-heavens-feel-2-lost-butterfly', 'Der Fall in die Verderbnis', 'arc-1', 10),
  ('fate', 'babylonia-singularity', 'fate-grand-order-babylonia', 'Die erste Singularität: Uruk', 'arc-3', 11),
  ('fate', 'hf-3-finale', 'fate-heavens-feel-3-spring-song', 'Das letzte Gefecht um Sakura', 'arc-1', 12),
  ('fate', 'camelot-round-table', 'fate-grand-order-camelot', 'Der Runde Tisch von Camelot', 'arc-3', 13);

INSERT INTO characters (universe_slug, work_slug, id, name, initials, sort_order) VALUES
  ('fate', 'fate-stay-night-2006', 'shirou-emiya-fsn', 'Shirou Emiya', 'SE', 0),
  ('fate', 'fate-zero', 'kiritsugu-emiya', 'Kiritsugu Emiya', 'KE', 1),
  ('fate', 'fate-prototype', 'arthur-pendragon-proto', 'Saber (Arthur Pendragon Prototype)', 'AP', 2),
  ('fate', 'fate-kaleid-liner-prisma-illya', 'illya-kaleid', 'Illyasviel von Einzbern', 'IE', 3),
  ('fate', 'fate-stay-night-unlimited-blade-works', 'rin-tohsaka', 'Rin Tohsaka', 'RT', 4),
  ('fate', 'fate-apocrypha', 'sieg-apocrypha', 'Sieg', 'SI', 5),
  ('fate', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'miyu-edelfelt-oath', 'Miyu Edelfelt', 'ME', 6),
  ('fate', 'fate-heavens-feel-1-presage-flower', 'sakura-matou-hf', 'Sakura Matou', 'SM', 7),
  ('fate', 'fate-grand-order-moonlight-lostroom', 'ritsuka-fujimaru', 'Ritsuka Fujimaru', 'RF', 8),
  ('fate', 'todays-menu-for-the-emiya-family', 'shirou-emiya-gohan', 'Shirou Emiya', 'SE', 9),
  ('fate', 'fate-heavens-feel-2-lost-butterfly', 'shirou-emiya-hf', 'Shirou Emiya', 'SE', 10),
  ('fate', 'fate-grand-order-babylonia', 'mash-kyrielight', 'Mash Kyrielight', 'MK', 11),
  ('fate', 'fate-heavens-feel-3-spring-song', 'illyasviel-hf', 'Illyasviel von Einzbern', 'IE', 12),
  ('fate', 'fate-grand-order-camelot', 'lancelot-camelot', 'Lancelot', 'LA', 13);

INSERT INTO plot_points (universe_slug, id, work_slug, character_id, arc_id, at, text) VALUES
  ('fate', 'pp-stay-night-1', 'fate-stay-night-2006', 'shirou-emiya-fsn', 'stay-night-fate-route', 1, 'Shirou Emiya wird ungewollt in den fünften Heiligen Gralkrieg gezogen und beschwört Saber.'),
  ('fate', 'pp-zero-1', 'fate-zero', 'kiritsugu-emiya', 'zero-fourth-war', 1, 'Kiritsugu Emiya kämpft als Meister von Saber im vierten Heiligen Gralkrieg um den Gral.'),
  ('fate', 'pp-proto-1', 'fate-prototype', 'arthur-pendragon-proto', 'proto-tokyo-1991', 1, 'Arthur Pendragon kämpft im Tokio-Gralkrieg von 1991 an der Seite von Manaka Sajyou.'),
  ('fate', 'pp-prisma-illya-1', 'fate-kaleid-liner-prisma-illya', 'illya-kaleid', 'prisma-illya-transformation', 1, 'Illyasviel wird von Magical Ruby zur Kaleidscope-Magical-Girl gemacht und muss Klassenkarten sammeln.'),
  ('fate', 'pp-ubw-1', 'fate-stay-night-unlimited-blade-works', 'rin-tohsaka', 'ubw-route', 1, 'Rin Tohsaka führt Shirou durch ihre Route des Gralkriegs und stellt ihn Archer gegenüber.'),
  ('fate', 'pp-apocrypha-1', 'fate-apocrypha', 'sieg-apocrypha', 'apocrypha-great-war', 1, 'Der Homunculus Sieg entkommt als Ersatz-Servant der Roten Fraktion und sucht seinen eigenen Weg.'),
  ('fate', 'pp-oath-1', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'miyu-edelfelt-oath', 'prisma-oath-shirou', 45, 'Shirou Emiya gewinnt den Ainsworth-Gralkrieg in einer einzigen Nacht, um Miyu in eine andere Welt zu retten.'),
  ('fate', 'pp-hf1-1', 'fate-heavens-feel-1-presage-flower', 'sakura-matou-hf', 'hf-1-shadow', 10, 'Sakura Matous dunkles Geheimnis beginnt Shirous Welt zu erschüttern.'),
  ('fate', 'pp-lostroom-1', 'fate-grand-order-moonlight-lostroom', 'ritsuka-fujimaru', 'fgo-lostbelt-prologue', 5, 'Ritsuka Fujimaru und Mash Kyrielight entdecken zu Weihnachten Chaldeas verborgenen ''Lost Room''.'),
  ('fate', 'pp-gohan-1', 'todays-menu-for-the-emiya-family', 'shirou-emiya-gohan', 'gohan-alltag', 1, 'Shirou kocht ein saisonales Gericht und bringt Rin, Sakura und Taiga an einen gemeinsamen Tisch.'),
  ('fate', 'pp-hf2-1', 'fate-heavens-feel-2-lost-butterfly', 'shirou-emiya-hf', 'hf-2-corruption', 60, 'Shirou nimmt Angra Mainyus Makel in sich auf, um Sakura zu retten.'),
  ('fate', 'pp-babylonia-1', 'fate-grand-order-babylonia', 'mash-kyrielight', 'babylonia-singularity', 3, 'Mash Kyrielight begleitet den Meister ins alte Uruk, die erste verlorene Singularität.'),
  ('fate', 'pp-hf3-1', 'fate-heavens-feel-3-spring-song', 'illyasviel-hf', 'hf-3-finale', 90, 'Illyasviel von Einzbern opfert sich im finalen Kampf um Sakuras Erlösung.'),
  ('fate', 'pp-camelot-1', 'fate-grand-order-camelot', 'lancelot-camelot', 'camelot-round-table', 30, 'Lancelot verteidigt als Wahnsinniger Ritter die Tafelrunde gegen Chaldeas Meister.');

-- Wizarding World

INSERT INTO universes (slug, name, sort_order) VALUES
  ('wizarding-world', 'Wizarding World', 2);

INSERT INTO sagas (universe_slug, id, name, tone, sort_order) VALUES
  ('wizarding-world', 'new-salem', 'Phantastische-Tierwesen-Ära', 'arc-2', 0),
  ('wizarding-world', 'hogwarts', 'Hogwarts-Ära', 'arc-1', 1);

INSERT INTO works (universe_slug, slug, title, short, kind, released, chronology, lore_date, saga_id, required, unit, range_start, range_end, now_playing, sort_order) VALUES
  ('wizarding-world', 'fantastic-beasts-1', 'Phantastische Tierwesen und wo sie zu finden sind', 'Phantastische Tierwesen', 'film', '2016-11-17', 10, '1926', 'new-salem', 1, 'Min.', 0, 133, NULL, 0),
  ('wizarding-world', 'fantastic-beasts-2', 'Phantastische Tierwesen: Grindelwalds Verbrechen', 'Grindelwalds Verbrechen', 'film', '2018-11-14', 20, '1927', 'new-salem', 1, 'Min.', 0, 134, NULL, 1),
  ('wizarding-world', 'fantastic-beasts-3', 'Phantastische Tierwesen: Dumbledores Geheimnisse', 'Dumbledores Geheimnisse', 'film', '2022-04-06', 30, '1932', 'new-salem', 1, 'Min.', 0, 142, NULL, 2),
  ('wizarding-world', 'philosophers-stone', 'Harry Potter und der Stein der Weisen', 'Stein der Weisen', 'film', '2001-11-16', 40, '1991', 'hogwarts', 1, 'Min.', 0, 152, NULL, 3),
  ('wizarding-world', 'chamber-of-secrets', 'Harry Potter und die Kammer des Schreckens', 'Kammer des Schreckens', 'film', '2002-11-15', 50, '1992', 'hogwarts', 1, 'Min.', 0, 161, NULL, 4),
  ('wizarding-world', 'prisoner-of-azkaban', 'Harry Potter und der Gefangene von Askaban', 'Gefangene von Askaban', 'film', '2004-06-04', 60, '1993', 'hogwarts', 1, 'Min.', 0, 142, NULL, 5),
  ('wizarding-world', 'goblet-of-fire', 'Harry Potter und der Feuerkelch', 'Feuerkelch', 'film', '2005-11-18', 70, '1994', 'hogwarts', 1, 'Min.', 0, 157, NULL, 6),
  ('wizarding-world', 'order-of-the-phoenix', 'Harry Potter und der Orden des Phönix', 'Orden des Phönix', 'film', '2007-07-11', 80, '1995', 'hogwarts', 1, 'Min.', 0, 138, NULL, 7),
  ('wizarding-world', 'half-blood-prince', 'Harry Potter und der Halbblutprinz', 'Halbblutprinz', 'film', '2009-07-15', 90, '1996', 'hogwarts', 1, 'Min.', 0, 153, NULL, 8),
  ('wizarding-world', 'deathly-hallows-1', 'Harry Potter und die Heiligtümer des Todes – Teil 1', 'Heiligtümer des Todes 1', 'film', '2010-11-19', 100, '1997', 'hogwarts', 1, 'Min.', 0, 146, NULL, 9),
  ('wizarding-world', 'deathly-hallows-2', 'Harry Potter und die Heiligtümer des Todes – Teil 2', 'Heiligtümer des Todes 2', 'film', '2011-07-13', 110, '1997–98', 'hogwarts', 1, 'Min.', 0, 130, NULL, 10);

INSERT INTO arcs (universe_slug, id, work_slug, name, tone, sort_order) VALUES
  ('wizarding-world', 'fb1-koffer', 'fantastic-beasts-1', 'Der Koffer voller Tierwesen', 'arc-1', 0),
  ('wizarding-world', 'fb1-schatten', 'fantastic-beasts-1', 'Grindelwalds Schatten', 'arc-3', 1),
  ('wizarding-world', 'fb2-aufstieg', 'fantastic-beasts-2', 'Grindelwalds Aufstieg', 'arc-3', 2),
  ('wizarding-world', 'fb2-herkunft', 'fantastic-beasts-2', 'Credences Herkunft', 'arc-1', 3),
  ('wizarding-world', 'fb3-wahl', 'fantastic-beasts-3', 'Die Zaubererwahl', 'arc-1', 4),
  ('wizarding-world', 'fb3-pakt', 'fantastic-beasts-3', 'Der Blutpakt', 'arc-3', 5),
  ('wizarding-world', 'ps-entdeckung', 'philosophers-stone', 'Die Entdeckung der Zaubererwelt', 'arc-1', 6),
  ('wizarding-world', 'ps-stein', 'philosophers-stone', 'Der Stein der Weisen', 'arc-3', 7),
  ('wizarding-world', 'cos-kammer', 'chamber-of-secrets', 'Die Kammer des Schreckens', 'arc-3', 8),
  ('wizarding-world', 'cos-freundschaft', 'chamber-of-secrets', 'Freundschaft und Vertrauen', 'arc-1', 9),
  ('wizarding-world', 'poa-sirius', 'prisoner-of-azkaban', 'Sirius Black', 'arc-2', 10),
  ('wizarding-world', 'poa-zeitumkehrer', 'prisoner-of-azkaban', 'Der Zeitumkehrer', 'arc-1', 11),
  ('wizarding-world', 'gof-turnier', 'goblet-of-fire', 'Das Trimagische Turnier', 'arc-1', 12),
  ('wizarding-world', 'gof-voldemort', 'goblet-of-fire', 'Voldemorts Rückkehr', 'arc-3', 13),
  ('wizarding-world', 'ootp-widerstand', 'order-of-the-phoenix', 'Dumbledores Armee', 'arc-1', 14),
  ('wizarding-world', 'ootp-prophezeiung', 'order-of-the-phoenix', 'Die Prophezeiung', 'arc-3', 15),
  ('wizarding-world', 'hbp-erinnerungen', 'half-blood-prince', 'Voldemorts Vergangenheit', 'arc-1', 16),
  ('wizarding-world', 'hbp-snape', 'half-blood-prince', 'Der Halbblutprinz', 'arc-3', 17),
  ('wizarding-world', 'dh1-flucht', 'deathly-hallows-1', 'Die Flucht aus Privet Drive', 'arc-1', 18),
  ('wizarding-world', 'dh1-horkruxe', 'deathly-hallows-1', 'Die Jagd nach Horkruxen', 'arc-3', 19),
  ('wizarding-world', 'dh2-hogwarts', 'deathly-hallows-2', 'Die Schlacht um Hogwarts', 'arc-1', 20),
  ('wizarding-world', 'dh2-ende', 'deathly-hallows-2', 'Voldemorts Ende', 'arc-3', 21);

INSERT INTO characters (universe_slug, work_slug, id, name, initials, sort_order) VALUES
  ('wizarding-world', 'fantastic-beasts-1', 'newt-fb1', 'Newt Scamander', 'NS', 0),
  ('wizarding-world', 'fantastic-beasts-1', 'tina-fb1', 'Tina Goldstein', 'TG', 1),
  ('wizarding-world', 'fantastic-beasts-1', 'jacob-fb1', 'Jacob Kowalski', 'JK', 2),
  ('wizarding-world', 'fantastic-beasts-1', 'credence-fb1', 'Credence Barebone', 'CB', 3),
  ('wizarding-world', 'fantastic-beasts-2', 'newt-fb2', 'Newt Scamander', 'NS', 4),
  ('wizarding-world', 'fantastic-beasts-2', 'grindelwald-fb2', 'Gellert Grindelwald', 'GG', 5),
  ('wizarding-world', 'fantastic-beasts-2', 'credence-fb2', 'Credence Barebone', 'CB', 6),
  ('wizarding-world', 'fantastic-beasts-2', 'dumbledore-fb2', 'Albus Dumbledore', 'AD', 7),
  ('wizarding-world', 'fantastic-beasts-3', 'newt-fb3', 'Newt Scamander', 'NS', 8),
  ('wizarding-world', 'fantastic-beasts-3', 'dumbledore-fb3', 'Albus Dumbledore', 'AD', 9),
  ('wizarding-world', 'fantastic-beasts-3', 'grindelwald-fb3', 'Gellert Grindelwald', 'GG', 10),
  ('wizarding-world', 'fantastic-beasts-3', 'credence-fb3', 'Credence Barebone', 'CB', 11),
  ('wizarding-world', 'philosophers-stone', 'harry-ps', 'Harry Potter', 'HP', 12),
  ('wizarding-world', 'philosophers-stone', 'ron-ps', 'Ron Weasley', 'RW', 13),
  ('wizarding-world', 'philosophers-stone', 'hermine-ps', 'Hermine Granger', 'HG', 14),
  ('wizarding-world', 'philosophers-stone', 'quirrell-ps', 'Professor Quirrell', 'PQ', 15),
  ('wizarding-world', 'chamber-of-secrets', 'harry-cos', 'Harry Potter', 'HP', 16),
  ('wizarding-world', 'chamber-of-secrets', 'ron-cos', 'Ron Weasley', 'RW', 17),
  ('wizarding-world', 'chamber-of-secrets', 'hermine-cos', 'Hermine Granger', 'HG', 18),
  ('wizarding-world', 'chamber-of-secrets', 'riddle-cos', 'Tom Riddle', 'TR', 19),
  ('wizarding-world', 'prisoner-of-azkaban', 'harry-poa', 'Harry Potter', 'HP', 20),
  ('wizarding-world', 'prisoner-of-azkaban', 'ron-poa', 'Ron Weasley', 'RW', 21),
  ('wizarding-world', 'prisoner-of-azkaban', 'hermine-poa', 'Hermine Granger', 'HG', 22),
  ('wizarding-world', 'prisoner-of-azkaban', 'sirius-poa', 'Sirius Black', 'SB', 23),
  ('wizarding-world', 'goblet-of-fire', 'harry-gof', 'Harry Potter', 'HP', 24),
  ('wizarding-world', 'goblet-of-fire', 'ron-gof', 'Ron Weasley', 'RW', 25),
  ('wizarding-world', 'goblet-of-fire', 'hermine-gof', 'Hermine Granger', 'HG', 26),
  ('wizarding-world', 'goblet-of-fire', 'voldemort-gof', 'Lord Voldemort', 'LV', 27),
  ('wizarding-world', 'order-of-the-phoenix', 'harry-ootp', 'Harry Potter', 'HP', 28),
  ('wizarding-world', 'order-of-the-phoenix', 'hermine-ootp', 'Hermine Granger', 'HG', 29),
  ('wizarding-world', 'order-of-the-phoenix', 'umbridge-ootp', 'Dolores Umbridge', 'DU', 30),
  ('wizarding-world', 'order-of-the-phoenix', 'sirius-ootp', 'Sirius Black', 'SB', 31),
  ('wizarding-world', 'half-blood-prince', 'harry-hbp', 'Harry Potter', 'HP', 32),
  ('wizarding-world', 'half-blood-prince', 'draco-hbp', 'Draco Malfoy', 'DM', 33),
  ('wizarding-world', 'half-blood-prince', 'snape-hbp', 'Severus Snape', 'SS', 34),
  ('wizarding-world', 'half-blood-prince', 'dumbledore-hbp', 'Albus Dumbledore', 'AD', 35),
  ('wizarding-world', 'deathly-hallows-1', 'harry-dh1', 'Harry Potter', 'HP', 36),
  ('wizarding-world', 'deathly-hallows-1', 'ron-dh1', 'Ron Weasley', 'RW', 37),
  ('wizarding-world', 'deathly-hallows-1', 'hermine-dh1', 'Hermine Granger', 'HG', 38),
  ('wizarding-world', 'deathly-hallows-1', 'dobby-dh1', 'Dobby', 'DO', 39),
  ('wizarding-world', 'deathly-hallows-2', 'harry-dh2', 'Harry Potter', 'HP', 40),
  ('wizarding-world', 'deathly-hallows-2', 'snape-dh2', 'Severus Snape', 'SS', 41),
  ('wizarding-world', 'deathly-hallows-2', 'voldemort-dh2', 'Lord Voldemort', 'LV', 42),
  ('wizarding-world', 'deathly-hallows-2', 'neville-dh2', 'Neville Longbottom', 'NL', 43);

INSERT INTO plot_points (universe_slug, id, work_slug, character_id, arc_id, at, text) VALUES
  ('wizarding-world', 'pp-fb1-1', 'fantastic-beasts-1', 'newt-fb1', 'fb1-koffer', 5, 'Schmuggelt seinen magischen Koffer voller Fantastischer Tierwesen mit nach New York.'),
  ('wizarding-world', 'pp-fb1-2', 'fantastic-beasts-1', 'newt-fb1', 'fb1-koffer', 80, 'Jagt gemeinsam mit Jacob die entkommenen Tierwesen quer durch New York.'),
  ('wizarding-world', 'pp-fb1-3', 'fantastic-beasts-1', 'tina-fb1', 'fb1-koffer', 20, 'Verhaftet Newt wegen des Verdachts illegaler Zauberei.'),
  ('wizarding-world', 'pp-fb1-4', 'fantastic-beasts-1', 'jacob-fb1', 'fb1-koffer', 15, 'Vertauscht als No-Maj versehentlich seinen Koffer mit Newts magischem Exemplar.'),
  ('wizarding-world', 'pp-fb1-5', 'fantastic-beasts-1', 'credence-fb1', 'fb1-schatten', 60, 'Wird von Graves als Werkzeug gegen die eigene Ziehmutter benutzt.'),
  ('wizarding-world', 'pp-fb1-6', 'fantastic-beasts-1', 'credence-fb1', 'fb1-schatten', 120, 'Entpuppt sich als Ursprung des zerstörerischen Obscurus.'),
  ('wizarding-world', 'pp-fb2-1', 'fantastic-beasts-2', 'newt-fb2', 'fb2-herkunft', 10, 'Wird von Dumbledore gebeten, Credence in Paris aufzuspüren, bevor Grindelwald ihn findet.'),
  ('wizarding-world', 'pp-fb2-2', 'fantastic-beasts-2', 'grindelwald-fb2', 'fb2-aufstieg', 5, 'Entkommt seiner Gefangenschaft und beginnt, Anhänger für seine reinblütige Vision zu sammeln.'),
  ('wizarding-world', 'pp-fb2-3', 'fantastic-beasts-2', 'grindelwald-fb2', 'fb2-aufstieg', 125, 'Enthüllt Credence eine Lüge über dessen wahre Herkunft, um ihn auf seine Seite zu ziehen.'),
  ('wizarding-world', 'pp-fb2-4', 'fantastic-beasts-2', 'credence-fb2', 'fb2-herkunft', 90, 'Sucht in Paris verzweifelt nach seiner echten Familie.'),
  ('wizarding-world', 'pp-fb2-5', 'fantastic-beasts-2', 'dumbledore-fb2', 'fb2-aufstieg', 15, 'Kann Grindelwald wegen eines alten Blutpakts nicht selbst entgegentreten.'),
  ('wizarding-world', 'pp-fb3-1', 'fantastic-beasts-3', 'newt-fb3', 'fb3-wahl', 20, 'Schmiedet mit Dumbledores Verbündeten einen Plan gegen Grindelwalds Wahlkampagne.'),
  ('wizarding-world', 'pp-fb3-2', 'fantastic-beasts-3', 'dumbledore-fb3', 'fb3-pakt', 30, 'Erklärt seinen Verbündeten den Blutpakt, der ihn an Grindelwald bindet.'),
  ('wizarding-world', 'pp-fb3-3', 'fantastic-beasts-3', 'dumbledore-fb3', 'fb3-pakt', 135, 'Zerstört im entscheidenden Duell den Blutpakt endgültig.'),
  ('wizarding-world', 'pp-fb3-4', 'fantastic-beasts-3', 'grindelwald-fb3', 'fb3-wahl', 100, 'Kandidiert offen für das Amt des Supreme Mugwump des Zaubererbunds.'),
  ('wizarding-world', 'pp-fb3-5', 'fantastic-beasts-3', 'credence-fb3', 'fb3-pakt', 110, 'Wendet sich im entscheidenden Moment gegen Grindelwald.'),
  ('wizarding-world', 'pp-ps-1', 'philosophers-stone', 'harry-ps', 'ps-entdeckung', 20, 'Erfährt von Hagrid, dass er ein Zauberer ist.'),
  ('wizarding-world', 'pp-ps-2', 'philosophers-stone', 'harry-ps', 'ps-stein', 140, 'Stellt sich Quirrell und Voldemort im Kampf um den Stein der Weisen.'),
  ('wizarding-world', 'pp-ps-3', 'philosophers-stone', 'ron-ps', 'ps-entdeckung', 45, 'Freundet sich mit Harry im Hogwarts-Express an.'),
  ('wizarding-world', 'pp-ps-4', 'philosophers-stone', 'hermine-ps', 'ps-entdeckung', 60, 'Rettet Harry und Ron vor einem Bergtroll und wird ihre Freundin.'),
  ('wizarding-world', 'pp-ps-5', 'philosophers-stone', 'quirrell-ps', 'ps-stein', 145, 'Wird als Wirt Voldemorts enttarnt, der in seinem Hinterkopf lebt.'),
  ('wizarding-world', 'pp-cos-1', 'chamber-of-secrets', 'harry-cos', 'cos-kammer', 30, 'Hört eine unheimliche Stimme, die nur er wahrnehmen kann.'),
  ('wizarding-world', 'pp-cos-2', 'chamber-of-secrets', 'harry-cos', 'cos-kammer', 150, 'Tötet den Basilisken tief in der Kammer des Schreckens.'),
  ('wizarding-world', 'pp-cos-3', 'chamber-of-secrets', 'ron-cos', 'cos-freundschaft', 10, 'Fliegt mit Harry im fliegenden Ford Anglia nach Hogwarts.'),
  ('wizarding-world', 'pp-cos-4', 'chamber-of-secrets', 'hermine-cos', 'cos-kammer', 100, 'Wird durch den Basilisken-Blick versteinert.'),
  ('wizarding-world', 'pp-cos-5', 'chamber-of-secrets', 'riddle-cos', 'cos-kammer', 120, 'Enthüllt sich als Tom Riddles Erinnerung, die auf Ginnys Seele zehrt.'),
  ('wizarding-world', 'pp-poa-1', 'prisoner-of-azkaban', 'harry-poa', 'poa-sirius', 30, 'Erfährt, dass der entflohene Sirius Black hinter ihm her sein soll.'),
  ('wizarding-world', 'pp-poa-2', 'prisoner-of-azkaban', 'harry-poa', 'poa-zeitumkehrer', 130, 'Rettet mit Hermines Zeitumkehrer Sirius und Seidenschnabel vor der Hinrichtung.'),
  ('wizarding-world', 'pp-poa-3', 'prisoner-of-azkaban', 'hermine-poa', 'poa-zeitumkehrer', 30, 'Nutzt heimlich einen Zeitumkehrer, um mehrere Kurse gleichzeitig zu besuchen.'),
  ('wizarding-world', 'pp-poa-4', 'prisoner-of-azkaban', 'ron-poa', 'poa-sirius', 95, 'Wird bei der Verfolgung von Sirius'' Animagus-Ratte in die Peitschende Weide gezogen.'),
  ('wizarding-world', 'pp-poa-5', 'prisoner-of-azkaban', 'sirius-poa', 'poa-sirius', 100, 'Enthüllt, dass nicht er, sondern Peter Pettigrew die Potters verraten hat.'),
  ('wizarding-world', 'pp-gof-1', 'goblet-of-fire', 'harry-gof', 'gof-turnier', 40, 'Wird trotz Mindestalter unfreiwillig als vierter Champion ausgewählt.'),
  ('wizarding-world', 'pp-gof-2', 'goblet-of-fire', 'harry-gof', 'gof-voldemort', 150, 'Entkommt nur knapp Voldemorts Wiedergeburt auf dem Friedhof.'),
  ('wizarding-world', 'pp-gof-3', 'goblet-of-fire', 'ron-gof', 'gof-turnier', 60, 'Zerstreitet sich mit Harry aus Eifersucht über dessen Teilnahme.'),
  ('wizarding-world', 'pp-gof-4', 'goblet-of-fire', 'hermine-gof', 'gof-turnier', 110, 'Geht mit Viktor Krum zum Weihnachtsball.'),
  ('wizarding-world', 'pp-gof-5', 'goblet-of-fire', 'voldemort-gof', 'gof-voldemort', 145, 'Erlangt durch ein dunkles Ritual einen neuen, vollständigen Körper zurück.'),
  ('wizarding-world', 'pp-ootp-1', 'order-of-the-phoenix', 'harry-ootp', 'ootp-widerstand', 70, 'Gründet heimlich Dumbledores Armee, um echte Verteidigung zu lehren.'),
  ('wizarding-world', 'pp-ootp-2', 'order-of-the-phoenix', 'harry-ootp', 'ootp-prophezeiung', 130, 'Erfährt im Zaubereiministerium den vollen Wortlaut der Prophezeiung.'),
  ('wizarding-world', 'pp-ootp-3', 'order-of-the-phoenix', 'hermine-ootp', 'ootp-widerstand', 65, 'Schlägt die Gründung von Dumbledores Armee vor.'),
  ('wizarding-world', 'pp-ootp-4', 'order-of-the-phoenix', 'umbridge-ootp', 'ootp-widerstand', 20, 'Übernimmt als neue Lehrerin die zunehmende Kontrolle über Hogwarts.'),
  ('wizarding-world', 'pp-ootp-5', 'order-of-the-phoenix', 'sirius-ootp', 'ootp-prophezeiung', 132, 'Stirbt im Duell mit Bellatrix Lestrange im Ministerium.'),
  ('wizarding-world', 'pp-hbp-1', 'half-blood-prince', 'harry-hbp', 'hbp-erinnerungen', 50, 'Sammelt mit Dumbledore Erinnerungen über Voldemorts Jugend.'),
  ('wizarding-world', 'pp-hbp-2', 'half-blood-prince', 'harry-hbp', 'hbp-snape', 145, 'Muss mit ansehen, wie Snape Dumbledore tötet.'),
  ('wizarding-world', 'pp-hbp-3', 'half-blood-prince', 'draco-hbp', 'hbp-snape', 100, 'Erhält von Voldemort den Auftrag, Dumbledore zu töten.'),
  ('wizarding-world', 'pp-hbp-4', 'half-blood-prince', 'snape-hbp', 'hbp-snape', 148, 'Erfüllt den Unbrechbaren Schwur und tötet Dumbledore auf dem Astronomieturm.'),
  ('wizarding-world', 'pp-hbp-5', 'half-blood-prince', 'dumbledore-hbp', 'hbp-erinnerungen', 60, 'Zeigt Harry, wie Voldemort erstmals einen Horkrux erschuf.'),
  ('wizarding-world', 'pp-dh1-1', 'deathly-hallows-1', 'harry-dh1', 'dh1-flucht', 10, 'Flieht mit sieben Doppelgängern vor den Todessern aus Privet Drive.'),
  ('wizarding-world', 'pp-dh1-2', 'deathly-hallows-1', 'harry-dh1', 'dh1-horkruxe', 120, 'Zerstört gemeinsam mit Ron Slytherins Medaillon-Horkrux.'),
  ('wizarding-world', 'pp-dh1-3', 'deathly-hallows-1', 'ron-dh1', 'dh1-horkruxe', 90, 'Verlässt aus Eifersucht und Erschöpfung vorübergehend seine Freunde.'),
  ('wizarding-world', 'pp-dh1-4', 'deathly-hallows-1', 'hermine-dh1', 'dh1-flucht', 5, 'Löscht das Gedächtnis ihrer Eltern, um sie vor Voldemort zu schützen.'),
  ('wizarding-world', 'pp-dh1-5', 'deathly-hallows-1', 'dobby-dh1', 'dh1-flucht', 140, 'Rettet die Gruppe aus Malfoy Manor und stirbt dabei.'),
  ('wizarding-world', 'pp-dh2-1', 'deathly-hallows-2', 'harry-dh2', 'dh2-hogwarts', 40, 'Bricht in die Verliese von Gringotts ein, um einen weiteren Horkrux zu holen.'),
  ('wizarding-world', 'pp-dh2-2', 'deathly-hallows-2', 'harry-dh2', 'dh2-ende', 125, 'Besiegt Voldemort endgültig in der Großen Halle von Hogwarts.'),
  ('wizarding-world', 'pp-dh2-3', 'deathly-hallows-2', 'snape-dh2', 'dh2-ende', 60, 'Offenbart in seinen letzten Erinnerungen seine wahre Loyalität zu Lily Potter.'),
  ('wizarding-world', 'pp-dh2-4', 'deathly-hallows-2', 'voldemort-dh2', 'dh2-ende', 128, 'Stirbt durch seinen eigenen zurückschlagenden Todesfluch.'),
  ('wizarding-world', 'pp-dh2-5', 'deathly-hallows-2', 'neville-dh2', 'dh2-hogwarts', 110, 'Enthauptet mit Gryffindors Schwert die Schlange Nagini.');

-- Marvel Cinematic Universe

INSERT INTO universes (slug, name, sort_order) VALUES
  ('mcu', 'Marvel Cinematic Universe', 3);

INSERT INTO sagas (universe_slug, id, name, tone, sort_order) VALUES
  ('mcu', 'origins', 'Ursprünge', 'arc-2', 0),
  ('mcu', 'rise-of-the-avengers', 'Infinity Saga: Rise of the Avengers', 'arc-1', 1),
  ('mcu', 'thanos', 'Infinity Saga: Thanos', 'arc-3', 2),
  ('mcu', 'multiverse-saga', 'Multiverse Saga', 'arc-2', 3);

INSERT INTO works (universe_slug, slug, title, short, kind, released, chronology, lore_date, saga_id, required, unit, range_start, range_end, now_playing, sort_order) VALUES
  ('mcu', 'captain-america-first-avenger', 'Captain America: The First Avenger', 'The First Avenger', 'film', '2011-07-22', 10, '1943–45', 'origins', 1, 'Min.', 0, 124, NULL, 0),
  ('mcu', 'captain-marvel', 'Captain Marvel', 'Captain Marvel', 'film', '2019-03-08', 20, '1995', 'origins', 1, 'Min.', 0, 124, NULL, 1),
  ('mcu', 'iron-man', 'Iron Man', 'Iron Man', 'film', '2008-05-02', 30, '2010', 'rise-of-the-avengers', 1, 'Min.', 0, 126, NULL, 2),
  ('mcu', 'the-incredible-hulk', 'The Incredible Hulk', 'The Incredible Hulk', 'film', '2008-06-13', 40, '2010', 'rise-of-the-avengers', 0, 'Min.', 0, 112, NULL, 3),
  ('mcu', 'iron-man-2', 'Iron Man 2', 'Iron Man 2', 'film', '2010-05-07', 50, '2011', 'rise-of-the-avengers', 1, 'Min.', 0, 124, NULL, 4),
  ('mcu', 'thor', 'Thor', 'Thor', 'film', '2011-05-06', 60, '2011', 'rise-of-the-avengers', 1, 'Min.', 0, 115, NULL, 5),
  ('mcu', 'the-avengers', 'The Avengers', 'The Avengers', 'film', '2012-05-04', 70, '2012', 'rise-of-the-avengers', 1, 'Min.', 0, 143, NULL, 6),
  ('mcu', 'iron-man-3', 'Iron Man 3', 'Iron Man 3', 'film', '2013-05-03', 80, '2013', 'rise-of-the-avengers', 1, 'Min.', 0, 130, NULL, 7),
  ('mcu', 'thor-dark-world', 'Thor: The Dark World', 'The Dark World', 'film', '2013-11-08', 90, '2013', 'rise-of-the-avengers', 0, 'Min.', 0, 112, NULL, 8),
  ('mcu', 'captain-america-winter-soldier', 'Captain America: The Winter Soldier', 'The Winter Soldier', 'film', '2014-04-04', 100, '2014', 'rise-of-the-avengers', 1, 'Min.', 0, 136, NULL, 9),
  ('mcu', 'guardians-of-the-galaxy', 'Guardians of the Galaxy', 'Guardians of the Galaxy', 'film', '2014-08-01', 110, '2014', 'rise-of-the-avengers', 1, 'Min.', 0, 121, NULL, 10),
  ('mcu', 'guardians-of-the-galaxy-vol-2', 'Guardians of the Galaxy Vol. 2', 'Guardians Vol. 2', 'film', '2017-05-05', 115, '2014', 'rise-of-the-avengers', 0, 'Min.', 0, 136, NULL, 11),
  ('mcu', 'avengers-age-of-ultron', 'Avengers: Age of Ultron', 'Age of Ultron', 'film', '2015-05-01', 120, '2015', 'rise-of-the-avengers', 1, 'Min.', 0, 141, NULL, 12),
  ('mcu', 'ant-man', 'Ant-Man', 'Ant-Man', 'film', '2015-07-17', 130, '2015', 'rise-of-the-avengers', 0, 'Min.', 0, 117, NULL, 13),
  ('mcu', 'captain-america-civil-war', 'Captain America: Civil War', 'Civil War', 'film', '2016-05-06', 140, '2016', 'thanos', 1, 'Min.', 0, 147, NULL, 14),
  ('mcu', 'black-panther', 'Black Panther', 'Black Panther', 'film', '2018-02-16', 145, '2016–17', 'thanos', 0, 'Min.', 0, 134, NULL, 15),
  ('mcu', 'doctor-strange', 'Doctor Strange', 'Doctor Strange', 'film', '2016-11-04', 148, '2016', 'thanos', 1, 'Min.', 0, 115, NULL, 16),
  ('mcu', 'spider-man-homecoming', 'Spider-Man: Homecoming', 'Homecoming', 'film', '2017-07-07', 150, '2016', 'thanos', 0, 'Min.', 0, 133, NULL, 17),
  ('mcu', 'thor-ragnarok', 'Thor: Ragnarok', 'Ragnarok', 'film', '2017-11-03', 155, '2017', 'thanos', 1, 'Min.', 0, 130, NULL, 18),
  ('mcu', 'ant-man-and-the-wasp', 'Ant-Man and the Wasp', 'Ant-Man and the Wasp', 'film', '2018-07-06', 158, '2018', 'thanos', 0, 'Min.', 0, 118, NULL, 19),
  ('mcu', 'avengers-infinity-war', 'Avengers: Infinity War', 'Infinity War', 'film', '2018-04-27', 160, '2018', 'thanos', 1, 'Min.', 0, 149, NULL, 20),
  ('mcu', 'avengers-endgame', 'Avengers: Endgame', 'Endgame', 'film', '2019-04-26', 170, '2018–2023', 'thanos', 1, 'Min.', 0, 181, NULL, 21),
  ('mcu', 'spider-man-far-from-home', 'Spider-Man: Far From Home', 'Far From Home', 'film', '2019-07-02', 175, '2023', 'thanos', 0, 'Min.', 0, 129, NULL, 22),
  ('mcu', 'wandavision', 'WandaVision', 'WandaVision', 'serie', '2021-01-15', 180, '2023', 'multiverse-saga', 0, 'Folge', 1, 9, NULL, 23),
  ('mcu', 'loki', 'Loki', 'Loki', 'serie', '2021-06-09', 185, '2012–2023', 'multiverse-saga', 1, 'Folge', 1, 6, NULL, 24),
  ('mcu', 'hawkeye', 'Hawkeye', 'Hawkeye', 'serie', '2021-11-24', 188, '2024', 'multiverse-saga', 0, 'Folge', 1, 6, NULL, 25),
  ('mcu', 'spider-man-no-way-home', 'Spider-Man: No Way Home', 'No Way Home', 'film', '2021-12-17', 190, '2024', 'multiverse-saga', 1, 'Min.', 0, 148, NULL, 26);

INSERT INTO arcs (universe_slug, id, work_slug, name, tone, sort_order) VALUES
  ('mcu', 'cm-erwachen', 'captain-marvel', 'Erwachen der Kräfte', 'arc-1', 0),
  ('mcu', 'cm-skrulls', 'captain-marvel', 'Die Skrull-Verschwörung', 'arc-3', 1),
  ('mcu', 'cafa-supersoldat', 'captain-america-first-avenger', 'Der Supersoldat', 'arc-1', 2),
  ('mcu', 'cafa-hydra', 'captain-america-first-avenger', 'Hydra', 'arc-3', 3),
  ('mcu', 'im-hoehle', 'iron-man', 'Die Höhle', 'arc-1', 4),
  ('mcu', 'im-verrat', 'iron-man', 'Stanes Verrat', 'arc-3', 5),
  ('mcu', 'hulk-flucht', 'the-incredible-hulk', 'Die Flucht', 'arc-1', 6),
  ('mcu', 'hulk-abomination', 'the-incredible-hulk', 'Abomination', 'arc-3', 7),
  ('mcu', 'im2-vergiftung', 'iron-man-2', 'Die Palladium-Vergiftung', 'arc-1', 8),
  ('mcu', 'im2-vanko', 'iron-man-2', 'Vankos Rache', 'arc-3', 9),
  ('mcu', 'thor-verbannung', 'thor', 'Die Verbannung', 'arc-1', 10),
  ('mcu', 'thor-loki', 'thor', 'Lokis Verrat', 'arc-3', 11),
  ('mcu', 'av-tesserakt', 'the-avengers', 'Das Tesserakt', 'arc-1', 12),
  ('mcu', 'av-invasion', 'the-avengers', 'Die Invasion von New York', 'arc-3', 13),
  ('mcu', 'tdw-aether', 'thor-dark-world', 'Der Äther', 'arc-1', 14),
  ('mcu', 'tdw-dunkelelfen', 'thor-dark-world', 'Die Dunkelelfen', 'arc-3', 15),
  ('mcu', 'im3-angst', 'iron-man-3', 'Panikattacken', 'arc-1', 16),
  ('mcu', 'im3-mandarin', 'iron-man-3', 'Der falsche Mandarin', 'arc-3', 17),
  ('mcu', 'tws-hydra', 'captain-america-winter-soldier', 'Hydra in SHIELD', 'arc-1', 18),
  ('mcu', 'tws-soldat', 'captain-america-winter-soldier', 'Der Winter Soldier', 'arc-3', 19),
  ('mcu', 'gotg-orb', 'guardians-of-the-galaxy', 'Die Orb', 'arc-1', 20),
  ('mcu', 'gotg-ronan', 'guardians-of-the-galaxy', 'Ronan der Ankläger', 'arc-3', 21),
  ('mcu', 'gotg2-vater', 'guardians-of-the-galaxy-vol-2', 'Peters Vater', 'arc-1', 22),
  ('mcu', 'gotg2-ego', 'guardians-of-the-galaxy-vol-2', 'Egos wahre Absicht', 'arc-3', 23),
  ('mcu', 'aou-schoepfung', 'avengers-age-of-ultron', 'Ultrons Erschaffung', 'arc-1', 24),
  ('mcu', 'aou-sokovia', 'avengers-age-of-ultron', 'Die Schlacht um Sokovia', 'arc-3', 25),
  ('mcu', 'am-anzug', 'ant-man', 'Der Anzug', 'arc-1', 26),
  ('mcu', 'am-diebstahl', 'ant-man', 'Der große Diebstahl', 'arc-3', 27),
  ('mcu', 'cw-abkommen', 'captain-america-civil-war', 'Das Sokovia-Abkommen', 'arc-1', 28),
  ('mcu', 'cw-spaltung', 'captain-america-civil-war', 'Die Spaltung der Avengers', 'arc-3', 29),
  ('mcu', 'bp-thron', 'black-panther', 'Der Thron von Wakanda', 'arc-1', 30),
  ('mcu', 'bp-killmonger', 'black-panther', 'Killmongers Anspruch', 'arc-3', 31),
  ('mcu', 'ds-unfall', 'doctor-strange', 'Der Unfall', 'arc-1', 32),
  ('mcu', 'ds-dormammu', 'doctor-strange', 'Dormammu', 'arc-3', 33),
  ('mcu', 'smh-schulalltag', 'spider-man-homecoming', 'Schulalltag und Heldentum', 'arc-1', 34),
  ('mcu', 'smh-vulture', 'spider-man-homecoming', 'Der Vulture', 'arc-3', 35),
  ('mcu', 'tr-sakaar', 'thor-ragnarok', 'Gefangen auf Sakaar', 'arc-1', 36),
  ('mcu', 'tr-hela', 'thor-ragnarok', 'Helas Rückkehr', 'arc-3', 37),
  ('mcu', 'amw-quantenreich', 'ant-man-and-the-wasp', 'Das Quantenreich', 'arc-1', 38),
  ('mcu', 'amw-rettung', 'ant-man-and-the-wasp', 'Die Rettung Janets', 'arc-3', 39),
  ('mcu', 'iw-steine', 'avengers-infinity-war', 'Die Suche nach den Steinen', 'arc-1', 40),
  ('mcu', 'iw-schnipp', 'avengers-infinity-war', 'Der Schnipp', 'arc-3', 41),
  ('mcu', 'eg-zeitreise', 'avengers-endgame', 'Die Zeitreise', 'arc-1', 42),
  ('mcu', 'eg-finale', 'avengers-endgame', 'Die letzte Schlacht', 'arc-3', 43),
  ('mcu', 'smffh-trauer', 'spider-man-far-from-home', 'Trauer um Tony', 'arc-1', 44),
  ('mcu', 'smffh-mysterio', 'spider-man-far-from-home', 'Mysterios Täuschung', 'arc-3', 45),
  ('mcu', 'wv-sitcom', 'wandavision', 'Die Sitcom-Illusion', 'arc-1', 46),
  ('mcu', 'wv-agatha', 'wandavision', 'Agathas Wahrheit', 'arc-3', 47),
  ('mcu', 'l-tva', 'loki', 'Die TVA', 'arc-1', 48),
  ('mcu', 'l-he-who-remains', 'loki', 'Der, welcher bleibt', 'arc-3', 49),
  ('mcu', 'hk-mentor', 'hawkeye', 'Mentor und Schülerin', 'arc-1', 50),
  ('mcu', 'hk-rache', 'hawkeye', 'Ronins Vermächtnis', 'arc-3', 51),
  ('mcu', 'nwh-zauber', 'spider-man-no-way-home', 'Der missglückte Zauber', 'arc-1', 52),
  ('mcu', 'nwh-multiversum', 'spider-man-no-way-home', 'Besucher aus dem Multiversum', 'arc-3', 53);

INSERT INTO characters (universe_slug, work_slug, id, name, initials, sort_order) VALUES
  ('mcu', 'captain-marvel', 'carol-cm', 'Carol Danvers', 'CD', 0),
  ('mcu', 'captain-marvel', 'fury-cm', 'Nick Fury', 'NF', 1),
  ('mcu', 'captain-marvel', 'yon-rogg-cm', 'Yon-Rogg', 'YR', 2),
  ('mcu', 'captain-america-first-avenger', 'steve-cafa', 'Steve Rogers', 'SR', 3),
  ('mcu', 'captain-america-first-avenger', 'bucky-cafa', 'Bucky Barnes', 'BB', 4),
  ('mcu', 'captain-america-first-avenger', 'red-skull-cafa', 'Red Skull', 'RS', 5),
  ('mcu', 'iron-man', 'tony-im', 'Tony Stark', 'TS', 6),
  ('mcu', 'iron-man', 'obadiah-im', 'Obadiah Stane', 'OS', 7),
  ('mcu', 'iron-man', 'rhodey-im', 'James Rhodes', 'JR', 8),
  ('mcu', 'the-incredible-hulk', 'bruce-hulk', 'Bruce Banner', 'BB2', 9),
  ('mcu', 'the-incredible-hulk', 'ross-hulk', 'General Ross', 'GR', 10),
  ('mcu', 'the-incredible-hulk', 'blonsky-hulk', 'Emil Blonsky', 'EB', 11),
  ('mcu', 'iron-man-2', 'tony-im2', 'Tony Stark', 'TS', 12),
  ('mcu', 'iron-man-2', 'whiplash-im2', 'Ivan Vanko', 'IV', 13),
  ('mcu', 'iron-man-2', 'natasha-im2', 'Natasha Romanoff', 'NR', 14),
  ('mcu', 'thor', 'thor-thor', 'Thor', 'TH', 15),
  ('mcu', 'thor', 'loki-thor', 'Loki', 'LO', 16),
  ('mcu', 'thor', 'jane-thor', 'Jane Foster', 'JF', 17),
  ('mcu', 'the-avengers', 'tony-av', 'Tony Stark', 'TS', 18),
  ('mcu', 'the-avengers', 'steve-av', 'Steve Rogers', 'SR', 19),
  ('mcu', 'the-avengers', 'natasha-av', 'Natasha Romanoff', 'NR', 20),
  ('mcu', 'the-avengers', 'loki-av', 'Loki', 'LO', 21),
  ('mcu', 'the-avengers', 'thor-av', 'Thor', 'TH', 22),
  ('mcu', 'thor-dark-world', 'thor-tdw', 'Thor', 'TH', 23),
  ('mcu', 'thor-dark-world', 'jane-tdw', 'Jane Foster', 'JF', 24),
  ('mcu', 'thor-dark-world', 'loki-tdw', 'Loki', 'LO', 25),
  ('mcu', 'iron-man-3', 'tony-im3', 'Tony Stark', 'TS', 26),
  ('mcu', 'iron-man-3', 'mandarin-im3', 'Aldrich Killian', 'AK', 27),
  ('mcu', 'iron-man-3', 'pepper-im3', 'Pepper Potts', 'PP', 28),
  ('mcu', 'captain-america-winter-soldier', 'steve-tws', 'Steve Rogers', 'SR', 29),
  ('mcu', 'captain-america-winter-soldier', 'bucky-tws', 'Bucky Barnes', 'BB', 30),
  ('mcu', 'captain-america-winter-soldier', 'natasha-tws', 'Natasha Romanoff', 'NR', 31),
  ('mcu', 'guardians-of-the-galaxy', 'peter-gotg', 'Peter Quill', 'PQ', 32),
  ('mcu', 'guardians-of-the-galaxy', 'gamora-gotg', 'Gamora', 'GA', 33),
  ('mcu', 'guardians-of-the-galaxy', 'rocket-gotg', 'Rocket', 'RO', 34),
  ('mcu', 'guardians-of-the-galaxy-vol-2', 'peter-gotg2', 'Peter Quill', 'PQ', 35),
  ('mcu', 'guardians-of-the-galaxy-vol-2', 'gamora-gotg2', 'Gamora', 'GA', 36),
  ('mcu', 'guardians-of-the-galaxy-vol-2', 'ego-gotg2', 'Ego', 'EG', 37),
  ('mcu', 'avengers-age-of-ultron', 'tony-aou', 'Tony Stark', 'TS', 38),
  ('mcu', 'avengers-age-of-ultron', 'ultron-aou', 'Ultron', 'UL', 39),
  ('mcu', 'avengers-age-of-ultron', 'wanda-aou', 'Wanda Maximoff', 'WM', 40),
  ('mcu', 'avengers-age-of-ultron', 'vision-aou', 'Vision', 'VI', 41),
  ('mcu', 'ant-man', 'scott-am', 'Scott Lang', 'SL', 42),
  ('mcu', 'ant-man', 'hank-am', 'Hank Pym', 'HP', 43),
  ('mcu', 'ant-man', 'hope-am', 'Hope van Dyne', 'HV', 44),
  ('mcu', 'captain-america-civil-war', 'steve-cw', 'Steve Rogers', 'SR', 45),
  ('mcu', 'captain-america-civil-war', 'tony-cw', 'Tony Stark', 'TS', 46),
  ('mcu', 'captain-america-civil-war', 'bucky-cw', 'Bucky Barnes', 'BB', 47),
  ('mcu', 'captain-america-civil-war', 'zemo-cw', 'Zemo', 'ZE', 48),
  ('mcu', 'black-panther', 'tchalla-bp', 'T''Challa', 'TC', 49),
  ('mcu', 'black-panther', 'killmonger-bp', 'Erik Killmonger', 'EK', 50),
  ('mcu', 'black-panther', 'shuri-bp', 'Shuri', 'SH', 51),
  ('mcu', 'doctor-strange', 'stephen-ds', 'Stephen Strange', 'SS', 52),
  ('mcu', 'doctor-strange', 'mordo-ds', 'Karl Mordo', 'KM', 53),
  ('mcu', 'doctor-strange', 'ancient-one-ds', 'Der Uralte', 'DU', 54),
  ('mcu', 'spider-man-homecoming', 'peter-smh', 'Peter Parker', 'PP2', 55),
  ('mcu', 'spider-man-homecoming', 'vulture-smh', 'Adrian Toomes', 'AT', 56),
  ('mcu', 'spider-man-homecoming', 'tony-smh', 'Tony Stark', 'TS', 57),
  ('mcu', 'thor-ragnarok', 'thor-tr', 'Thor', 'TH', 58),
  ('mcu', 'thor-ragnarok', 'hulk-tr', 'Bruce Banner', 'BB2', 59),
  ('mcu', 'thor-ragnarok', 'hela-tr', 'Hela', 'HE', 60),
  ('mcu', 'thor-ragnarok', 'loki-tr', 'Loki', 'LO', 61),
  ('mcu', 'ant-man-and-the-wasp', 'scott-amw', 'Scott Lang', 'SL', 62),
  ('mcu', 'ant-man-and-the-wasp', 'hope-amw', 'Hope van Dyne', 'HV', 63),
  ('mcu', 'ant-man-and-the-wasp', 'janet-amw', 'Janet van Dyne', 'JV', 64),
  ('mcu', 'avengers-infinity-war', 'tony-iw', 'Tony Stark', 'TS', 65),
  ('mcu', 'avengers-infinity-war', 'thanos-iw', 'Thanos', 'TH2', 66),
  ('mcu', 'avengers-infinity-war', 'thor-iw', 'Thor', 'TH', 67),
  ('mcu', 'avengers-infinity-war', 'steve-iw', 'Steve Rogers', 'SR', 68),
  ('mcu', 'avengers-endgame', 'tony-eg', 'Tony Stark', 'TS', 69),
  ('mcu', 'avengers-endgame', 'steve-eg', 'Steve Rogers', 'SR', 70),
  ('mcu', 'avengers-endgame', 'natasha-eg', 'Natasha Romanoff', 'NR', 71),
  ('mcu', 'avengers-endgame', 'thanos-eg', 'Thanos', 'TH2', 72),
  ('mcu', 'spider-man-far-from-home', 'peter-smffh', 'Peter Parker', 'PP2', 73),
  ('mcu', 'spider-man-far-from-home', 'mysterio-smffh', 'Quentin Beck', 'QB', 74),
  ('mcu', 'spider-man-far-from-home', 'happy-smffh', 'Happy Hogan', 'HH', 75),
  ('mcu', 'wandavision', 'wanda-wv', 'Wanda Maximoff', 'WM', 76),
  ('mcu', 'wandavision', 'vision-wv', 'Vision', 'VI', 77),
  ('mcu', 'wandavision', 'agatha-wv', 'Agatha Harkness', 'AH', 78),
  ('mcu', 'loki', 'loki-l', 'Loki', 'LO', 79),
  ('mcu', 'loki', 'mobius-l', 'Mobius M. Mobius', 'MM', 80),
  ('mcu', 'loki', 'sylvie-l', 'Sylvie', 'SY', 81),
  ('mcu', 'hawkeye', 'clint-hk', 'Clint Barton', 'CB', 82),
  ('mcu', 'hawkeye', 'kate-hk', 'Kate Bishop', 'KB', 83),
  ('mcu', 'hawkeye', 'yelena-hk', 'Yelena Belova', 'YB', 84),
  ('mcu', 'spider-man-no-way-home', 'peter-nwh', 'Peter Parker', 'PP2', 85),
  ('mcu', 'spider-man-no-way-home', 'strange-nwh', 'Stephen Strange', 'SS', 86),
  ('mcu', 'spider-man-no-way-home', 'green-goblin-nwh', 'Norman Osborn', 'NO', 87);

INSERT INTO plot_points (universe_slug, id, work_slug, character_id, arc_id, at, text) VALUES
  ('mcu', 'pp-cm-1', 'captain-marvel', 'carol-cm', 'cm-erwachen', 30, 'Erinnert sich in Bruchstücken an ein früheres Leben als Kree-Kriegerin.'),
  ('mcu', 'pp-cm-2', 'captain-marvel', 'carol-cm', 'cm-skrulls', 90, 'Erkennt, dass die Kree sie belogen haben, und wendet sich gegen sie.'),
  ('mcu', 'pp-cm-3', 'captain-marvel', 'fury-cm', 'cm-skrulls', 20, 'Begegnet erstmals einer außerirdischen Bedrohung und verliert dabei ein Auge.'),
  ('mcu', 'pp-cm-4', 'captain-marvel', 'yon-rogg-cm', 'cm-erwachen', 10, 'Trainiert Carol als Starforce-Kriegerin und unterdrückt ihre wahre Kraft.'),
  ('mcu', 'pp-cafa-1', 'captain-america-first-avenger', 'steve-cafa', 'cafa-supersoldat', 20, 'Wird vom schmächtigen Freiwilligen zum Supersoldaten Captain America.'),
  ('mcu', 'pp-cafa-2', 'captain-america-first-avenger', 'steve-cafa', 'cafa-hydra', 110, 'Stürzt das Schiff der Hydra ins Eis, um New York zu retten.'),
  ('mcu', 'pp-cafa-3', 'captain-america-first-avenger', 'bucky-cafa', 'cafa-hydra', 80, 'Stürzt bei einem Hydra-Einsatz scheinbar in den Tod.'),
  ('mcu', 'pp-cafa-4', 'captain-america-first-avenger', 'red-skull-cafa', 'cafa-hydra', 90, 'Wird von der Macht des Tesserakts ausgelöscht.'),
  ('mcu', 'pp-im-1', 'iron-man', 'tony-im', 'im-hoehle', 20, 'Baut in einer Höhle in Afghanistan den ersten Iron-Man-Anzug.'),
  ('mcu', 'pp-im-2', 'iron-man', 'tony-im', 'im-verrat', 115, 'Enttarnt sich öffentlich als Iron Man.'),
  ('mcu', 'pp-im-3', 'iron-man', 'obadiah-im', 'im-verrat', 90, 'Verrät Tony und baut selbst eine Rüstung, um ihn zu töten.'),
  ('mcu', 'pp-im-4', 'iron-man', 'rhodey-im', 'im-hoehle', 40, 'Findet Tony nach der Rettung aus der Wüste als Erster.'),
  ('mcu', 'pp-hulk-1', 'the-incredible-hulk', 'bruce-hulk', 'hulk-flucht', 10, 'Flieht quer durch Südamerika, um seine Verwandlung zu kontrollieren.'),
  ('mcu', 'pp-hulk-2', 'the-incredible-hulk', 'bruce-hulk', 'hulk-abomination', 95, 'Besiegt als Hulk das noch monströsere Abomination in Harlem.'),
  ('mcu', 'pp-hulk-3', 'the-incredible-hulk', 'ross-hulk', 'hulk-flucht', 15, 'Jagt Banner mit dem Militär durch mehrere Länder.'),
  ('mcu', 'pp-hulk-4', 'the-incredible-hulk', 'blonsky-hulk', 'hulk-abomination', 85, 'Lässt sich freiwillig zum Abomination mutieren.'),
  ('mcu', 'pp-im2-1', 'iron-man-2', 'tony-im2', 'im2-vergiftung', 15, 'Vergiftet sich langsam selbst durch den Palladium-Kern seines Reaktors.'),
  ('mcu', 'pp-im2-2', 'iron-man-2', 'tony-im2', 'im2-vanko', 110, 'Besiegt gemeinsam mit Rhodey Vankos Drohnenarmee.'),
  ('mcu', 'pp-im2-3', 'iron-man-2', 'whiplash-im2', 'im2-vanko', 60, 'Baut aus Rache an Starks Vater eigene Peitschen-Waffen.'),
  ('mcu', 'pp-im2-4', 'iron-man-2', 'natasha-im2', 'im2-vergiftung', 70, 'Infiltriert als Agentin Romanoff verdeckt Starks Firma.'),
  ('mcu', 'pp-thor-1', 'thor', 'thor-thor', 'thor-verbannung', 15, 'Wird von Odin wegen seines Hochmuts nach Midgard verbannt.'),
  ('mcu', 'pp-thor-2', 'thor', 'thor-thor', 'thor-loki', 100, 'Zerstört die Regenbogenbrücke, um Jotunheim vor Loki zu schützen.'),
  ('mcu', 'pp-thor-3', 'thor', 'loki-thor', 'thor-loki', 70, 'Erfährt seine wahre Herkunft als Jotunheim-Findelkind.'),
  ('mcu', 'pp-thor-4', 'thor', 'jane-thor', 'thor-verbannung', 20, 'Findet den vom Himmel gefallenen Thor in der Wüste von New Mexico.'),
  ('mcu', 'pp-av-1', 'the-avengers', 'loki-av', 'av-tesserakt', 5, 'Stiehlt das Tesserakt und übernimmt die Kontrolle über Agent Barton.'),
  ('mcu', 'pp-av-2', 'the-avengers', 'tony-av', 'av-invasion', 130, 'Lenkt eine Atomrakete durch das Wurmloch in die Chitauri-Flotte.'),
  ('mcu', 'pp-av-3', 'the-avengers', 'steve-av', 'av-invasion', 100, 'Übernimmt als Captain America die Feldführung der Avengers.'),
  ('mcu', 'pp-av-4', 'the-avengers', 'natasha-av', 'av-invasion', 90, 'Schließt mithilfe von Loki-Stab-Wissen das Portal über New York.'),
  ('mcu', 'pp-av-5', 'the-avengers', 'thor-av', 'av-tesserakt', 40, 'Versucht zunächst vergeblich, seinen Bruder von der Erde fortzubringen.'),
  ('mcu', 'pp-tdw-1', 'thor-dark-world', 'thor-tdw', 'tdw-dunkelelfen', 100, 'Verbündet sich heimlich mit Loki, um Malekith zu besiegen.'),
  ('mcu', 'pp-tdw-2', 'thor-dark-world', 'jane-tdw', 'tdw-aether', 20, 'Wird unabsichtlich zum Wirt des Äthers.'),
  ('mcu', 'pp-tdw-3', 'thor-dark-world', 'loki-tdw', 'tdw-dunkelelfen', 95, 'Täuscht seinen eigenen Tod vor, um Odins Thron zu übernehmen.'),
  ('mcu', 'pp-im3-1', 'iron-man-3', 'tony-im3', 'im3-angst', 10, 'Leidet nach New York unter schweren Panikattacken.'),
  ('mcu', 'pp-im3-2', 'iron-man-3', 'tony-im3', 'im3-mandarin', 120, 'Zerstört am Ende alle seine Anzüge, um mit Pepper neu anzufangen.'),
  ('mcu', 'pp-im3-3', 'iron-man-3', 'mandarin-im3', 'im3-mandarin', 60, 'Enttarnt den ''Mandarin'' als reine Schauspieler-Fassade.'),
  ('mcu', 'pp-im3-4', 'iron-man-3', 'pepper-im3', 'im3-mandarin', 115, 'Erhält durch Extremis übermenschliche Kräfte und rettet Tony.'),
  ('mcu', 'pp-tws-1', 'captain-america-winter-soldier', 'steve-tws', 'tws-hydra', 90, 'Deckt auf, dass Hydra SHIELD von innen unterwandert hat.'),
  ('mcu', 'pp-tws-2', 'captain-america-winter-soldier', 'bucky-tws', 'tws-soldat', 100, 'Erkennt Steve als seinen alten Freund und rettet ihn aus dem Fluss.'),
  ('mcu', 'pp-tws-3', 'captain-america-winter-soldier', 'natasha-tws', 'tws-hydra', 95, 'Veröffentlicht sämtliche SHIELD- und Hydra-Geheimnisse im Internet.'),
  ('mcu', 'pp-gotg-1', 'guardians-of-the-galaxy', 'peter-gotg', 'gotg-orb', 10, 'Stiehlt die geheimnisvolle Orb von einem verlassenen Planeten.'),
  ('mcu', 'pp-gotg-2', 'guardians-of-the-galaxy', 'gamora-gotg', 'gotg-ronan', 90, 'Wendet sich gegen ihren Ziehvater Thanos und Ronan.'),
  ('mcu', 'pp-gotg-3', 'guardians-of-the-galaxy', 'rocket-gotg', 'gotg-ronan', 100, 'Hilft, Ronans Schiff im entscheidenden Kampf über Xandar zu zerstören.'),
  ('mcu', 'pp-gotg2-1', 'guardians-of-the-galaxy-vol-2', 'peter-gotg2', 'gotg2-vater', 30, 'Trifft erstmals seinen leiblichen Vater Ego.'),
  ('mcu', 'pp-gotg2-2', 'guardians-of-the-galaxy-vol-2', 'gamora-gotg2', 'gotg2-vater', 110, 'Hilft Peter, sich gegen Egos Plan zu stellen.'),
  ('mcu', 'pp-gotg2-3', 'guardians-of-the-galaxy-vol-2', 'ego-gotg2', 'gotg2-ego', 100, 'Enthüllt seinen Plan, das ganze Universum mit sich zu verschmelzen.'),
  ('mcu', 'pp-aou-1', 'avengers-age-of-ultron', 'tony-aou', 'aou-schoepfung', 20, 'Erschafft heimlich die künstliche Intelligenz Ultron.'),
  ('mcu', 'pp-aou-2', 'avengers-age-of-ultron', 'ultron-aou', 'aou-sokovia', 120, 'Versucht, Sokovia als Meteor auf die Erde stürzen zu lassen.'),
  ('mcu', 'pp-aou-3', 'avengers-age-of-ultron', 'wanda-aou', 'aou-schoepfung', 60, 'Wendet sich nach einem Blick in Tonys Ängste gegen die Avengers.'),
  ('mcu', 'pp-aou-4', 'avengers-age-of-ultron', 'vision-aou', 'aou-sokovia', 100, 'Wird aus Vibranium erschaffen und erweist sich als würdig, Mjolnir zu heben.'),
  ('mcu', 'pp-am-1', 'ant-man', 'scott-am', 'am-anzug', 30, 'Erhält von Hank Pym den schrumpfenden Ant-Man-Anzug.'),
  ('mcu', 'pp-am-2', 'ant-man', 'hank-am', 'am-diebstahl', 90, 'Plant den Diebstahl der Yellowjacket-Technologie von Cross.'),
  ('mcu', 'pp-am-3', 'ant-man', 'hope-am', 'am-diebstahl', 100, 'Trainiert Scott für den entscheidenden Einbruch bei Cross.'),
  ('mcu', 'pp-cw-1', 'captain-america-civil-war', 'tony-cw', 'cw-abkommen', 20, 'Unterstützt aus Schuldgefühl das Sokovia-Abkommen zur Kontrolle der Avengers.'),
  ('mcu', 'pp-cw-2', 'captain-america-civil-war', 'steve-cw', 'cw-spaltung', 130, 'Verteidigt Bucky gegen die eigenen ehemaligen Verbündeten.'),
  ('mcu', 'pp-cw-3', 'captain-america-civil-war', 'bucky-cw', 'cw-spaltung', 50, 'Wird von Zemo als Winter Soldier reaktiviert und für einen Anschlag benutzt.'),
  ('mcu', 'pp-cw-4', 'captain-america-civil-war', 'zemo-cw', 'cw-spaltung', 140, 'Spaltet die Avengers gezielt durch die Enthüllung von Buckys Vergangenheit.'),
  ('mcu', 'pp-bp-1', 'black-panther', 'tchalla-bp', 'bp-thron', 20, 'Übernimmt nach dem Tod seines Vaters den Thron von Wakanda.'),
  ('mcu', 'pp-bp-2', 'black-panther', 'killmonger-bp', 'bp-killmonger', 90, 'Fordert T''Challa um den Thron heraus und gewinnt zunächst.'),
  ('mcu', 'pp-bp-3', 'black-panther', 'shuri-bp', 'bp-thron', 40, 'Entwickelt als Wakandas Technologiechefin neue Panther-Rüstungen.'),
  ('mcu', 'pp-ds-1', 'doctor-strange', 'stephen-ds', 'ds-unfall', 15, 'Verliert nach einem Autounfall die Feinmotorik seiner Hände.'),
  ('mcu', 'pp-ds-2', 'doctor-strange', 'stephen-ds', 'ds-dormammu', 100, 'Handelt mit Dormammu eine Zeitschleife aus, um die Erde zu retten.'),
  ('mcu', 'pp-ds-3', 'doctor-strange', 'mordo-ds', 'ds-unfall', 40, 'Führt Strange in die Kunst der Zauberei am Kamar-Taj ein.'),
  ('mcu', 'pp-ds-4', 'doctor-strange', 'ancient-one-ds', 'ds-unfall', 45, 'Zeigt Strange die Existenz der Multiversen und der Magie.'),
  ('mcu', 'pp-smh-1', 'spider-man-homecoming', 'peter-smh', 'smh-schulalltag', 10, 'Balanciert Highschool-Alltag mit seinem neuen Leben als Spider-Man.'),
  ('mcu', 'pp-smh-2', 'spider-man-homecoming', 'peter-smh', 'smh-vulture', 120, 'Besiegt den Vulture allein, ohne einen Iron-Man-Anzug.'),
  ('mcu', 'pp-smh-3', 'spider-man-homecoming', 'vulture-smh', 'smh-vulture', 30, 'Baut aus gestohlener Alien-Technologie gefährliche Flugwaffen.'),
  ('mcu', 'pp-tr-1', 'thor-ragnarok', 'thor-tr', 'tr-sakaar', 40, 'Wird als Gladiator auf dem Müllplaneten Sakaar gefangen gehalten.'),
  ('mcu', 'pp-tr-2', 'thor-ragnarok', 'thor-tr', 'tr-hela', 115, 'Löst bewusst Ragnarök aus, um Hela zu besiegen.'),
  ('mcu', 'pp-tr-3', 'thor-ragnarok', 'hulk-tr', 'tr-sakaar', 45, 'Tritt als amtierender Champion von Sakaar gegen Thor an.'),
  ('mcu', 'pp-tr-4', 'thor-ragnarok', 'hela-tr', 'tr-hela', 10, 'Kehrt aus der Verbannung zurück und zerstört Thors Hammer.'),
  ('mcu', 'pp-amw-1', 'ant-man-and-the-wasp', 'scott-amw', 'amw-quantenreich', 20, 'Steht unter Hausarrest nach den Ereignissen von Civil War.'),
  ('mcu', 'pp-amw-2', 'ant-man-and-the-wasp', 'hope-amw', 'amw-rettung', 100, 'Kämpft erstmals als Wasp an Scotts Seite.'),
  ('mcu', 'pp-amw-3', 'ant-man-and-the-wasp', 'janet-amw', 'amw-rettung', 110, 'Wird nach Jahrzehnten aus dem Quantenreich gerettet.'),
  ('mcu', 'pp-iw-1', 'avengers-infinity-war', 'thanos-iw', 'iw-steine', 20, 'Beginnt seinen Feldzug zur Sammlung aller sechs Infinity-Steine.'),
  ('mcu', 'pp-iw-2', 'avengers-infinity-war', 'thanos-iw', 'iw-schnipp', 145, 'Schnippt mit dem vollständigen Handschuh die Hälfte allen Lebens fort.'),
  ('mcu', 'pp-iw-3', 'avengers-infinity-war', 'tony-iw', 'iw-steine', 90, 'Kämpft mit Doctor Strange auf Titan gegen Thanos.'),
  ('mcu', 'pp-iw-4', 'avengers-infinity-war', 'thor-iw', 'iw-steine', 60, 'Lässt sich auf Nidavellir eine neue Waffe schmieden: Stormbreaker.'),
  ('mcu', 'pp-iw-5', 'avengers-infinity-war', 'steve-iw', 'iw-schnipp', 140, 'Muss hilflos mit ansehen, wie Bucky vor seinen Augen zerfällt.'),
  ('mcu', 'pp-eg-1', 'avengers-endgame', 'tony-eg', 'eg-zeitreise', 60, 'Findet nach fünf Jahren endlich eine funktionierende Zeitreise-Formel.'),
  ('mcu', 'pp-eg-2', 'avengers-endgame', 'tony-eg', 'eg-finale', 170, 'Schnippt selbst mit den Steinen und opfert sich, um Thanos zu besiegen.'),
  ('mcu', 'pp-eg-3', 'avengers-endgame', 'natasha-eg', 'eg-zeitreise', 90, 'Opfert sich auf Vormir, um den Seelenstein zu erhalten.'),
  ('mcu', 'pp-eg-4', 'avengers-endgame', 'steve-eg', 'eg-zeitreise', 100, 'Reist in der Zeit zurück, um die Infinity-Steine zurückzubringen.'),
  ('mcu', 'pp-eg-5', 'avengers-endgame', 'thanos-eg', 'eg-finale', 165, 'Reist aus der Vergangenheit an, um die Wiederherstellung zu verhindern.'),
  ('mcu', 'pp-smffh-1', 'spider-man-far-from-home', 'peter-smffh', 'smffh-trauer', 15, 'Sucht nach Tonys Tod verzweifelt nach einer neuen Normalität.'),
  ('mcu', 'pp-smffh-2', 'spider-man-far-from-home', 'peter-smffh', 'smffh-mysterio', 120, 'Enttarnt Mysterios Illusionen als reine Drohnen-Täuschung.'),
  ('mcu', 'pp-smffh-3', 'spider-man-far-from-home', 'mysterio-smffh', 'smffh-mysterio', 60, 'Gibt sich als Held aus einer anderen Erde aus, um Starks Erbe zu übernehmen.'),
  ('mcu', 'pp-smffh-4', 'spider-man-far-from-home', 'happy-smffh', 'smffh-trauer', 20, 'Unterstützt Peter als väterlicher Freund an Tonys Stelle.'),
  ('mcu', 'pp-wv-1', 'wandavision', 'wanda-wv', 'wv-sitcom', 3, 'Erschafft aus Trauer eine ganze Sitcom-Realität über Westview.'),
  ('mcu', 'pp-wv-2', 'wandavision', 'wanda-wv', 'wv-agatha', 8, 'Lässt die Hex-Realität los und trauert offen um Vision.'),
  ('mcu', 'pp-wv-4', 'wandavision', 'vision-wv', 'wv-sitcom', 1, 'Existiert als Wandas Konstrukt in der Sitcom-Illusion, ohne von ihrem Ursprung zu wissen.'),
  ('mcu', 'pp-wv-3', 'wandavision', 'agatha-wv', 'wv-agatha', 7, 'Enttarnt sich als Hexe hinter den Kulissen von Westview.'),
  ('mcu', 'pp-l-1', 'loki', 'loki-l', 'l-tva', 1, 'Wird von der TVA wegen einer Zeitlinien-Abweichung verhaftet.'),
  ('mcu', 'pp-l-2', 'loki', 'loki-l', 'l-he-who-remains', 6, 'Trifft am Ende der Zeit auf Er, welcher bleibt.'),
  ('mcu', 'pp-l-3', 'loki', 'mobius-l', 'l-tva', 2, 'Rekrutiert Loki, um einen gefährlichen Variantem zu jagen.'),
  ('mcu', 'pp-l-4', 'loki', 'sylvie-l', 'l-he-who-remains', 5, 'Enthüllt sich als weiblicher Loki-Variant auf eigener Rachemission.'),
  ('mcu', 'pp-hk-1', 'hawkeye', 'clint-hk', 'hk-mentor', 1, 'Bildet an Weihnachten notgedrungen die junge Kate Bishop aus.'),
  ('mcu', 'pp-hk-2', 'hawkeye', 'kate-hk', 'hk-mentor', 2, 'Trägt versehentlich Clints altes Ronin-Kostüm bei einer Auktion.'),
  ('mcu', 'pp-hk-3', 'hawkeye', 'yelena-hk', 'hk-rache', 4, 'Verfolgt Clint für den Tod ihrer Schwester Natasha.'),
  ('mcu', 'pp-nwh-1', 'spider-man-no-way-home', 'peter-nwh', 'nwh-zauber', 20, 'Bittet Strange, dass die ganze Welt seine Identität vergisst.'),
  ('mcu', 'pp-nwh-2', 'spider-man-no-way-home', 'peter-nwh', 'nwh-multiversum', 130, 'Heilt gemeinsam mit zwei anderen Spider-Men alle Multiversums-Besucher.'),
  ('mcu', 'pp-nwh-3', 'spider-man-no-way-home', 'strange-nwh', 'nwh-zauber', 25, 'Verpatzt den Gedächtniszauber, wodurch Risse im Multiversum entstehen.'),
  ('mcu', 'pp-nwh-4', 'spider-man-no-way-home', 'green-goblin-nwh', 'nwh-multiversum', 110, 'Verwundet May tödlich und stellt Peter vor seine schwerste Prüfung.');

-- Dragon Ball

INSERT INTO universes (slug, name, sort_order) VALUES
  ('dragon-ball', 'Dragon Ball', 4);

INSERT INTO sagas (universe_slug, id, name, tone, sort_order) VALUES
  ('dragon-ball', 'original', 'Dragon-Ball-Ära', 'arc-2', 0),
  ('dragon-ball', 'z-era', 'Dragon-Ball-Z-Ära', 'arc-1', 1),
  ('dragon-ball', 'super-era', 'Dragon-Ball-Super-Ära', 'arc-3', 2);

INSERT INTO works (universe_slug, slug, title, short, kind, released, chronology, lore_date, saga_id, required, unit, range_start, range_end, now_playing, sort_order) VALUES
  ('dragon-ball', 'dragon-ball-original', 'Dragon Ball', 'Dragon Ball', 'serie', '1986-02-26', 10, 'Kindheit von Son Goku', 'original', 1, 'Folge', 1, 153, NULL, 0),
  ('dragon-ball', 'dragon-ball-z', 'Dragon Ball Z', 'Dragon Ball Z', 'serie', '1989-04-26', 20, 'Erwachsenenalter von Son Goku', 'z-era', 1, 'Folge', 1, 291, NULL, 1),
  ('dragon-ball', 'dead-zone', 'Dragon Ball Z: Dead Zone', 'Dead Zone', 'film', '1989-07-15', 30, 'Kurz nach dem Saiyajin-Angriff', 'z-era', 0, 'Min.', 0, 46, NULL, 2),
  ('dragon-ball', 'coolers-revenge', 'Dragon Ball Z: Cooler''s Revenge', 'Cooler''s Revenge', 'film', '1991-07-20', 60, 'Nach Friezas Niederlage', 'z-era', 0, 'Min.', 0, 47, NULL, 3),
  ('dragon-ball', 'broly-legendary-super-saiyan', 'Dragon Ball Z: Broly – Der Legendäre Super-Saiyajin', 'Broly – Der Legendäre Super-Saiyajin', 'film', '1993-03-06', 85, 'Vor den Cell-Spielen', 'z-era', 0, 'Min.', 0, 70, NULL, 4),
  ('dragon-ball', 'fusion-reborn', 'Dragon Ball Z: Fusion Reborn', 'Fusion Reborn', 'film', '1995-03-04', 110, 'Nach Kid Buus Niederlage', 'z-era', 0, 'Min.', 0, 52, NULL, 5),
  ('dragon-ball', 'dragon-ball-super', 'Dragon Ball Super', 'Dragon Ball Super', 'serie', '2015-07-05', 130, 'Jahre nach Kid Buu', 'super-era', 1, 'Folge', 1, 131, NULL, 6),
  ('dragon-ball', 'dragon-ball-super-broly', 'Dragon Ball Super: Broly', 'Broly', 'film', '2018-12-14', 140, 'Nach dem Turnier der Kraft', 'super-era', 0, 'Min.', 0, 100, NULL, 7),
  ('dragon-ball', 'dragon-ball-super-super-hero', 'Dragon Ball Super: Super Hero', 'Super Hero', 'film', '2022-06-11', 150, 'Jahre nach Broly', 'super-era', 0, 'Min.', 0, 99, NULL, 8);

INSERT INTO seasons (universe_slug, work_slug, id, season_number, label, released, chronology, lore_date, range_start, range_end, sort_order) VALUES
  ('dragon-ball', 'dragon-ball-z', 'z-s1', 1, 'Saiyajin-Saga', '1989-04-26', 20, 'Ankunft der Saiyajin', 1, 39, 0),
  ('dragon-ball', 'dragon-ball-z', 'z-s2', 2, 'Namek- und Frieza-Saga', '1990-02-07', 40, 'Kampf um Namek', 40, 107, 1),
  ('dragon-ball', 'dragon-ball-z', 'z-s3', 3, 'Android- und Cell-Saga', '1991-10-08', 70, 'Die Android-Bedrohung', 108, 194, 2),
  ('dragon-ball', 'dragon-ball-z', 'z-s4', 4, 'Buu-Saga', '1993-11-24', 100, 'Majin Buus Erwachen', 195, 291, 3);

INSERT INTO arcs (universe_slug, id, work_slug, name, tone, sort_order) VALUES
  ('dragon-ball', 'db-suche', 'dragon-ball-original', 'Die Suche nach den Dragon Balls', 'arc-1', 0),
  ('dragon-ball', 'db-turnier', 'dragon-ball-original', 'Das Tenkaichi-Turnier', 'arc-2', 1),
  ('dragon-ball', 'z-saiyan', 'dragon-ball-z', 'Saiyan-Saga', 'arc-1', 2),
  ('dragon-ball', 'z-namek', 'dragon-ball-z', 'Namek-Saga', 'arc-2', 3),
  ('dragon-ball', 'z-android', 'dragon-ball-z', 'Android-Saga', 'arc-3', 4),
  ('dragon-ball', 'z-buu', 'dragon-ball-z', 'Buu-Saga', 'arc-1', 5),
  ('dragon-ball', 'dz-garlic', 'dead-zone', 'Garlic Jr.''s Rache', 'arc-3', 6),
  ('dragon-ball', 'cr-cooler', 'coolers-revenge', 'Coolers Rache', 'arc-3', 7),
  ('dragon-ball', 'bls-broly', 'broly-legendary-super-saiyan', 'Der Legendäre Super-Saiyajin', 'arc-3', 8),
  ('dragon-ball', 'fr-janemba', 'fusion-reborn', 'Janembas Chaos', 'arc-3', 9),
  ('dragon-ball', 'super-battle-of-gods', 'dragon-ball-super', 'Battle of Gods', 'arc-1', 10),
  ('dragon-ball', 'super-tournament-of-power', 'dragon-ball-super', 'Turnier der Kraft', 'arc-3', 11),
  ('dragon-ball', 'sbroly-broly', 'dragon-ball-super-broly', 'Brolys Rückkehr', 'arc-3', 12),
  ('dragon-ball', 'sh-red-ribbon', 'dragon-ball-super-super-hero', 'Die neue Red-Ribbon-Armee', 'arc-3', 13);

INSERT INTO characters (universe_slug, work_slug, id, name, initials, sort_order) VALUES
  ('dragon-ball', 'dragon-ball-original', 'goku-db', 'Son Goku', 'SG', 0),
  ('dragon-ball', 'dragon-ball-original', 'bulma-db', 'Bulma', 'BU', 1),
  ('dragon-ball', 'dragon-ball-original', 'roshi-db', 'Meister Roshi', 'MR', 2),
  ('dragon-ball', 'dragon-ball-z', 'goku-z', 'Son Goku', 'SG', 3),
  ('dragon-ball', 'dragon-ball-z', 'vegeta-z', 'Vegeta', 'VE', 4),
  ('dragon-ball', 'dragon-ball-z', 'gohan-z', 'Son Gohan', 'GO', 5),
  ('dragon-ball', 'dragon-ball-z', 'frieza-z', 'Frieza', 'FR', 6),
  ('dragon-ball', 'dragon-ball-z', 'cell-z', 'Cell', 'CE', 7),
  ('dragon-ball', 'dragon-ball-z', 'buu-z', 'Majin Buu', 'MB', 8),
  ('dragon-ball', 'dead-zone', 'goku-dz', 'Son Goku', 'SG', 9),
  ('dragon-ball', 'dead-zone', 'gohan-dz', 'Son Gohan', 'GO', 10),
  ('dragon-ball', 'coolers-revenge', 'goku-cr', 'Son Goku', 'SG', 11),
  ('dragon-ball', 'coolers-revenge', 'cooler-cr', 'Cooler', 'CO', 12),
  ('dragon-ball', 'broly-legendary-super-saiyan', 'goku-bls', 'Son Goku', 'SG', 13),
  ('dragon-ball', 'broly-legendary-super-saiyan', 'broly-bls', 'Broly', 'BR', 14),
  ('dragon-ball', 'fusion-reborn', 'goku-fr', 'Son Goku', 'SG', 15),
  ('dragon-ball', 'fusion-reborn', 'janemba-fr', 'Janemba', 'JA', 16),
  ('dragon-ball', 'dragon-ball-super', 'goku-super', 'Son Goku', 'SG', 17),
  ('dragon-ball', 'dragon-ball-super', 'vegeta-super', 'Vegeta', 'VE', 18),
  ('dragon-ball', 'dragon-ball-super', 'beerus-super', 'Beerus', 'BE', 19),
  ('dragon-ball', 'dragon-ball-super', 'jiren-super', 'Jiren', 'JI', 20),
  ('dragon-ball', 'dragon-ball-super-broly', 'goku-sbroly', 'Son Goku', 'SG', 21),
  ('dragon-ball', 'dragon-ball-super-broly', 'broly-sbroly', 'Broly', 'BR', 22),
  ('dragon-ball', 'dragon-ball-super-super-hero', 'gohan-sh', 'Son Gohan', 'GO', 23),
  ('dragon-ball', 'dragon-ball-super-super-hero', 'piccolo-sh', 'Piccolo', 'PI', 24);

INSERT INTO plot_points (universe_slug, id, work_slug, character_id, arc_id, at, text) VALUES
  ('dragon-ball', 'pp-db-1', 'dragon-ball-original', 'goku-db', 'db-suche', 5, 'Findet als Kind die Vier-Sterne-Dragon-Ball und beginnt die Reise mit Bulma.'),
  ('dragon-ball', 'pp-db-2', 'dragon-ball-original', 'bulma-db', 'db-suche', 10, 'Nimmt Goku mit auf die Suche nach allen sieben Dragon Balls.'),
  ('dragon-ball', 'pp-db-3', 'dragon-ball-original', 'roshi-db', 'db-turnier', 60, 'Bildet Goku im Kampf für das Tenkaichi-Turnier aus.'),
  ('dragon-ball', 'pp-z-1', 'dragon-ball-z', 'goku-z', 'z-saiyan', 20, 'Stirbt im Kampf gegen seinen Bruder Raditz, um die Erde zu retten.'),
  ('dragon-ball', 'pp-z-2', 'dragon-ball-z', 'vegeta-z', 'z-saiyan', 35, 'Greift gemeinsam mit Nappa die Erde an, um die Dragon Balls zu erobern.'),
  ('dragon-ball', 'pp-z-3', 'dragon-ball-z', 'gohan-z', 'z-namek', 90, 'Wird auf Namek unfreiwillig zum stärksten Kämpfer der Gruppe.'),
  ('dragon-ball', 'pp-z-4', 'dragon-ball-z', 'frieza-z', 'z-namek', 105, 'Wird von einem verwandelten Super-Saiyajin Goku besiegt.'),
  ('dragon-ball', 'pp-z-5', 'dragon-ball-z', 'cell-z', 'z-android', 180, 'Erreicht seine perfekte Form, indem er Android 17 und 18 absorbiert.'),
  ('dragon-ball', 'pp-z-6', 'dragon-ball-z', 'buu-z', 'z-buu', 270, 'Wird nach zahllosen Verwandlungen endgültig als Kid Buu ausgelöscht.'),
  ('dragon-ball', 'pp-dz-1', 'dead-zone', 'goku-dz', 'dz-garlic', 30, 'Kämpft gegen den wiederauferstandenen Garlic Jr. um Kamis Palast.'),
  ('dragon-ball', 'pp-dz-2', 'dead-zone', 'gohan-dz', 'dz-garlic', 15, 'Wird von Garlic Jr.''s Handlangern entführt.'),
  ('dragon-ball', 'pp-cr-1', 'coolers-revenge', 'goku-cr', 'cr-cooler', 35, 'Besiegt Friezas Bruder Cooler, der Rache für seinen Bruder sucht.'),
  ('dragon-ball', 'pp-cr-2', 'coolers-revenge', 'cooler-cr', 'cr-cooler', 10, 'Verfolgt Goku bis zur Erde, um den Tod seines Bruders zu rächen.'),
  ('dragon-ball', 'pp-bls-1', 'broly-legendary-super-saiyan', 'goku-bls', 'bls-broly', 55, 'Steht dem außer Kontrolle geratenen Broly als Super-Saiyajin gegenüber.'),
  ('dragon-ball', 'pp-bls-2', 'broly-legendary-super-saiyan', 'broly-bls', 'bls-broly', 20, 'Erwacht als der legendäre Super-Saiyajin mit grenzenloser Wut.'),
  ('dragon-ball', 'pp-fr-1', 'fusion-reborn', 'goku-fr', 'fr-janemba', 40, 'Fusioniert mit Vegeta zu Gogeta, um Janemba zu besiegen.'),
  ('dragon-ball', 'pp-fr-2', 'fusion-reborn', 'janemba-fr', 'fr-janemba', 15, 'Entsteht aus der Verzerrung der Hölle als reines Chaoswesen.'),
  ('dragon-ball', 'pp-super-1', 'dragon-ball-super', 'goku-super', 'super-battle-of-gods', 20, 'Weckt Beerus, den Gott der Zerstörung, versehentlich auf.'),
  ('dragon-ball', 'pp-super-2', 'dragon-ball-super', 'beerus-super', 'super-battle-of-gods', 40, 'Sucht nach einem würdigen Gegner, der sein Interesse weckt.'),
  ('dragon-ball', 'pp-super-3', 'dragon-ball-super', 'vegeta-super', 'super-tournament-of-power', 90, 'Kämpft im Turnier der Kraft um das Überleben seines Universums.'),
  ('dragon-ball', 'pp-super-4', 'dragon-ball-super', 'jiren-super', 'super-tournament-of-power', 110, 'Gilt als der stärkste Kämpfer im gesamten Turnier der Kraft.'),
  ('dragon-ball', 'pp-sbroly-1', 'dragon-ball-super-broly', 'goku-sbroly', 'sbroly-broly', 60, 'Kämpft gemeinsam mit Vegeta gegen den wiedergeborenen Broly.'),
  ('dragon-ball', 'pp-sbroly-2', 'dragon-ball-super-broly', 'broly-sbroly', 'sbroly-broly', 30, 'Wächst isoliert auf einem fernen Planeten zu unermesslicher Stärke heran.'),
  ('dragon-ball', 'pp-sh-1', 'dragon-ball-super-super-hero', 'gohan-sh', 'sh-red-ribbon', 70, 'Erwacht als Gohan Beast zu neuer, ungeahnter Stärke.'),
  ('dragon-ball', 'pp-sh-2', 'dragon-ball-super-super-hero', 'piccolo-sh', 'sh-red-ribbon', 50, 'Trainiert heimlich mit Pan und wird zu Orange Piccolo.');

