-- GENERIERT aus den früheren JSON-Universen; ab jetzt die Datenquelle.
-- Lokal:  bun run db:seed:local
-- Remote: bun run db:seed:remote

-- Umgekehrte Fremdschlüssel-Reihenfolge, damit der Seed wiederholbar ist.
DELETE FROM plot_points;
DELETE FROM characters;
DELETE FROM arcs;
DELETE FROM works;
DELETE FROM sagas;
DELETE FROM universes;

-- Star Wars

INSERT INTO universes (slug, name, sort_order) VALUES
  ('star-wars', 'Star Wars', 0);

INSERT INTO sagas (universe_slug, id, name, tone, sort_order) VALUES
  ('star-wars', 'high-republic', 'High Republic Era', 'arc-1', 0),
  ('star-wars', 'prequel', 'Prequel-Ära', 'arc-2', 1),
  ('star-wars', 'fall-of-the-jedi', 'Fall of the Jedi', 'arc-3', 2),
  ('star-wars', 'original', 'Original-Trilogie', 'arc-1', 3),
  ('star-wars', 'new-republic', 'New Republic Era', 'arc-2', 4),
  ('star-wars', 'rise-of-the-first-order', 'Rise of the First Order', 'arc-3', 5);

INSERT INTO works (universe_slug, slug, title, short, kind, released, chronology, lore_date, saga_id, required, unit, range_start, range_end, now_playing, sort_order) VALUES
  ('star-wars', 'young-jedi-adventures', 'Star Wars: Young Jedi Adventures', 'Young Jedi Adventures', 'serie', '2023-05-04', 1, '200 BBY', 'high-republic', 0, 'Folge', 1, 10, NULL, 0),
  ('star-wars', 'the-acolyte', 'The Acolyte', 'The Acolyte', 'serie', '2024-06-04', 5, '132 BBY', 'high-republic', 0, 'Folge', 1, 8, NULL, 1),
  ('star-wars', 'episode-i', 'Episode I – Die dunkle Bedrohung', 'Episode I', 'film', '1999-05-19', 10, '32 BBY', 'prequel', 1, 'Min.', 0, 136, NULL, 2),
  ('star-wars', 'episode-ii', 'Episode II – Angriff der Klonkrieger', 'Episode II', 'film', '2002-05-16', 20, '22 BBY', 'prequel', 1, 'Min.', 0, 142, NULL, 3),
  ('star-wars', 'the-clone-wars', 'The Clone Wars', 'Clone Wars', 'serie', '2008-10-03', 25, '22–19 BBY', 'prequel', 0, 'Folge', 1, 22, NULL, 4),
  ('star-wars', 'episode-iii', 'Episode III – Die Rache der Sith', 'Episode III', 'film', '2005-05-19', 30, '19 BBY', 'prequel', 1, 'Min.', 0, 140, NULL, 5),
  ('star-wars', 'bad-batch', 'Star Wars: The Bad Batch', 'The Bad Batch', 'serie', '2021-05-04', 33, '19 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 16, NULL, 6),
  ('star-wars', 'tales-of-the-empire', 'Tales of the Empire', 'Tales of the Empire', 'serie', '2024-05-04', 36, '19–9 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 6, NULL, 7),
  ('star-wars', 'obi-wan-kenobi', 'Obi-Wan Kenobi', 'Obi-Wan Kenobi', 'serie', '2022-05-27', 38, '9 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 6, NULL, 8),
  ('star-wars', 'solo', 'Solo', 'Solo', 'film', '2018-05-24', 40, '13 BBY', 'fall-of-the-jedi', 0, 'Min.', 0, 135, NULL, 9),
  ('star-wars', 'star-wars-rebels', 'Star Wars Rebels', 'Star Wars Rebels', 'serie', '2014-10-03', 55, '5–0 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 15, NULL, 10),
  ('star-wars', 'andor', 'Andor', 'Andor', 'serie', '2022-09-21', 58, '5–1 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 12, NULL, 11),
  ('star-wars', 'rogue-one', 'Rogue One', 'Rogue One', 'film', '2016-12-15', 60, '0 BBY', 'fall-of-the-jedi', 0, 'Min.', 0, 133, NULL, 12),
  ('star-wars', 'tales-of-the-underworld', 'Tales of the Underworld', 'Tales of the Underworld', 'serie', '2025-05-04', 62, '0 BBY', 'fall-of-the-jedi', 0, 'Folge', 1, 6, NULL, 13),
  ('star-wars', 'episode-iv', 'Episode IV – Eine neue Hoffnung', 'Episode IV', 'film', '1977-05-25', 70, '0 BBY', 'original', 1, 'Min.', 0, 121, NULL, 14),
  ('star-wars', 'episode-v', 'Episode V – Das Imperium schlägt zurück', 'Episode V', 'film', '1980-05-21', 80, '3 ABY', 'original', 1, 'Min.', 0, 124, NULL, 15),
  ('star-wars', 'episode-vi', 'Episode VI – Die Rückkehr der Jedi-Ritter', 'Episode VI', 'film', '1983-05-25', 90, '4 ABY', 'original', 1, 'Min.', 0, 131, NULL, 16),
  ('star-wars', 'the-mandalorian', 'The Mandalorian – Staffel 1', 'The Mandalorian', 'serie', '2019-11-12', 100, '9 ABY', 'new-republic', 1, 'Folge', 1, 8, NULL, 17),
  ('star-wars', 'book-of-boba-fett', 'The Book of Boba Fett', 'Book of Boba Fett', 'serie', '2021-12-29', 104, '9 ABY', 'new-republic', 0, 'Folge', 1, 7, NULL, 18),
  ('star-wars', 'skeleton-crew', 'Star Wars: Skeleton Crew', 'Skeleton Crew', 'serie', '2024-12-02', 107, '3 ABY', 'new-republic', 0, 'Folge', 1, 8, NULL, 19),
  ('star-wars', 'ahsoka', 'Ahsoka', 'Ahsoka', 'serie', '2023-08-22', 110, '9 ABY', 'new-republic', 0, 'Folge', 1, 8, NULL, 20),
  ('star-wars', 'maul-shadow-lord', 'Maul: Shadow Lord', 'Maul: Shadow Lord', 'serie', '2026-04-06', 115, '9 ABY', 'new-republic', 0, 'Folge', 1, 8, NULL, 21),
  ('star-wars', 'mandalorian-und-grogu', 'The Mandalorian & Grogu', 'Mandalorian & Grogu', 'film', '2026-05-22', 120, '10 ABY', 'new-republic', 1, 'Min.', 0, 130, 1, 22),
  ('star-wars', 'star-wars-resistance', 'Star Wars Resistance', 'Star Wars Resistance', 'serie', '2018-10-07', 125, '28–29 ABY', 'rise-of-the-first-order', 0, 'Folge', 1, 21, NULL, 23),
  ('star-wars', 'episode-vii', 'Episode VII – Das Erwachen der Macht', 'Episode VII', 'film', '2015-12-17', 130, '34 ABY', 'rise-of-the-first-order', 1, 'Min.', 0, 138, NULL, 24),
  ('star-wars', 'episode-viii', 'Episode VIII – Die letzten Jedi', 'Episode VIII', 'film', '2017-12-14', 140, '34 ABY', 'rise-of-the-first-order', 1, 'Min.', 0, 152, NULL, 25),
  ('star-wars', 'episode-ix', 'Episode IX – Der Aufstieg Skywalkers', 'Episode IX', 'film', '2019-12-18', 150, '35 ABY', 'rise-of-the-first-order', 1, 'Min.', 0, 142, NULL, 26);

INSERT INTO arcs (universe_slug, id, work_slug, name, tone, sort_order) VALUES
  ('star-wars', 'yja-tempel', 'young-jedi-adventures', 'Der Tempel', 'arc-1', 0),
  ('star-wars', 'yja-freundschaft', 'young-jedi-adventures', 'Freundschaft', 'arc-2', 1),
  ('star-wars', 'acolyte-schwestern', 'the-acolyte', 'Die Schwestern', 'arc-1', 2),
  ('star-wars', 'acolyte-jedi', 'the-acolyte', 'Die Jedi', 'arc-2', 3),
  ('star-wars', 'acolyte-schatten', 'the-acolyte', 'Der Schatten', 'arc-3', 4),
  ('star-wars', 'iv-held', 'episode-iv', 'Heldenreise', 'arc-1', 5),
  ('star-wars', 'iv-rebellion', 'episode-iv', 'Rebellion', 'arc-2', 6),
  ('star-wars', 'iv-imperium', 'episode-iv', 'Imperium', 'arc-3', 7),
  ('star-wars', 'batch-batch', 'bad-batch', 'Die Überlebenden', 'arc-1', 8),
  ('star-wars', 'batch-rat', 'bad-batch', 'Der Rat der Macht', 'arc-2', 9),
  ('star-wars', 'batch-imperium', 'bad-batch', 'Das Imperium', 'arc-3', 10),
  ('star-wars', 'tote-inquisitorin', 'tales-of-the-empire', 'Die Inquisitorin', 'arc-1', 11),
  ('star-wars', 'tote-dathomir', 'tales-of-the-empire', 'Dathomir', 'arc-2', 12),
  ('star-wars', 'kenobi-obi-wan', 'obi-wan-kenobi', 'Der verlorene Meister', 'arc-1', 13),
  ('star-wars', 'kenobi-anakin', 'obi-wan-kenobi', 'Der gefallene Schüler', 'arc-2', 14),
  ('star-wars', 'kenobi-vader', 'obi-wan-kenobi', 'Die Konfrontation', 'arc-3', 15),
  ('star-wars', 'rebels-ghost', 'star-wars-rebels', 'Die Crew der Ghost', 'arc-1', 16),
  ('star-wars', 'rebels-erwachen', 'star-wars-rebels', 'Das Erwachen der Rebellion', 'arc-2', 17),
  ('star-wars', 'rebels-imperium', 'star-wars-rebels', 'Das Imperium', 'arc-3', 18),
  ('star-wars', 'andor-cassian', 'andor', 'Cassians Weg', 'arc-1', 19),
  ('star-wars', 'andor-rebellion', 'andor', 'Die Rebellion', 'arc-2', 20),
  ('star-wars', 'andor-imperium', 'andor', 'Das Imperium', 'arc-3', 21),
  ('star-wars', 'totu-unterwelt', 'tales-of-the-underworld', 'Die Unterwelt', 'arc-3', 22),
  ('star-wars', 'm-kind', 'the-mandalorian', 'Das Kind', 'arc-1', 23),
  ('star-wars', 'm-gilde', 'the-mandalorian', 'Die Gilde', 'arc-2', 24),
  ('star-wars', 'm-gideon', 'the-mandalorian', 'Moff Gideon', 'arc-3', 25),
  ('star-wars', 'boba-thron', 'book-of-boba-fett', 'Der Thron', 'arc-1', 26),
  ('star-wars', 'boba-vergangenheit', 'book-of-boba-fett', 'Die Vergangenheit', 'arc-2', 27),
  ('star-wars', 'boba-tatooine', 'book-of-boba-fett', 'Tatooine', 'arc-3', 28),
  ('star-wars', 'sc-kinder', 'skeleton-crew', 'Die Kinder', 'arc-1', 29),
  ('star-wars', 'sc-jod', 'skeleton-crew', 'Jod Na Nawood', 'arc-2', 30),
  ('star-wars', 'sc-galaxis', 'skeleton-crew', 'Die Galaxis', 'arc-3', 31),
  ('star-wars', 'ahsoka-ahsoka', 'ahsoka', 'Die Rückkehr der Jedi', 'arc-1', 32),
  ('star-wars', 'ahsoka-din-djarin', 'ahsoka', 'Die Bande des Großen Geheimnisses', 'arc-2', 33),
  ('star-wars', 'ahsoka-empire', 'ahsoka', 'Das neue Imperium', 'arc-3', 34),
  ('star-wars', 'maul-schatten', 'maul-shadow-lord', 'Der Schattenlord', 'arc-1', 35),
  ('star-wars', 'maul-rache', 'maul-shadow-lord', 'Rache', 'arc-3', 36),
  ('star-wars', 'resistance-kaz', 'star-wars-resistance', 'Kazuda Xiono', 'arc-1', 37),
  ('star-wars', 'resistance-erste-ordnung', 'star-wars-resistance', 'Die Erste Ordnung', 'arc-3', 38);

INSERT INTO characters (universe_slug, work_slug, id, name, initials, sort_order) VALUES
  ('star-wars', 'young-jedi-adventures', 'kai-brightstar', 'Kai Brightstar', 'KB', 0),
  ('star-wars', 'young-jedi-adventures', 'lys-solay', 'Lys Solay', 'LS', 1),
  ('star-wars', 'young-jedi-adventures', 'nubs', 'Nubs', 'NU', 2),
  ('star-wars', 'the-acolyte', 'osha', 'Osha Aniseya', 'OA', 3),
  ('star-wars', 'the-acolyte', 'mae', 'Mae Aniseya', 'MA', 4),
  ('star-wars', 'the-acolyte', 'sol', 'Meister Sol', 'MS', 5),
  ('star-wars', 'the-acolyte', 'qimir', 'Qimir', 'QI', 6),
  ('star-wars', 'episode-iv', 'luke', 'Luke Skywalker', 'LS', 7),
  ('star-wars', 'episode-iv', 'leia', 'Leia Organa', 'LO', 8),
  ('star-wars', 'episode-iv', 'han', 'Han Solo', 'HS', 9),
  ('star-wars', 'episode-iv', 'vader', 'Darth Vader', 'DV', 10),
  ('star-wars', 'episode-iv', 'obi-wan', 'Obi-Wan Kenobi', 'OK', 11),
  ('star-wars', 'episode-iv', 'r2-d2', 'R2-D2', 'R2', 12),
  ('star-wars', 'episode-iv', 'c-3po', 'C-3PO', '3PO', 13),
  ('star-wars', 'episode-iv', 'tarkin', 'Grand Moff Tarkin', 'GT', 14),
  ('star-wars', 'episode-iv', 'chewbacca', 'Chewbacca', 'CH', 15),
  ('star-wars', 'bad-batch', 'hunter', 'Hunter', 'HU', 16),
  ('star-wars', 'bad-batch', 'omega', 'Omega', 'OM', 17),
  ('star-wars', 'bad-batch', 'crosshair', 'Crosshair', 'CH', 18),
  ('star-wars', 'bad-batch', 'nala-se', 'Nala Se', 'NS', 19),
  ('star-wars', 'tales-of-the-empire', 'morgan-elsbeth', 'Morgan Elsbeth', 'ME', 20),
  ('star-wars', 'tales-of-the-empire', 'barriss', 'Barriss Offee', 'BO', 21),
  ('star-wars', 'obi-wan-kenobi', 'obi-wan', 'Obi-Wan Kenobi', 'OK', 22),
  ('star-wars', 'obi-wan-kenobi', 'leia-organa', 'Leia Organa', 'LO', 23),
  ('star-wars', 'obi-wan-kenobi', 'vader', 'Darth Vader', 'DV', 24),
  ('star-wars', 'obi-wan-kenobi', 'reva', 'Reva Sevander', 'RS', 25),
  ('star-wars', 'star-wars-rebels', 'ezra', 'Ezra Bridger', 'EB', 26),
  ('star-wars', 'star-wars-rebels', 'kanan', 'Kanan Jarrus', 'KJ', 27),
  ('star-wars', 'star-wars-rebels', 'hera', 'Hera Syndulla', 'HS', 28),
  ('star-wars', 'star-wars-rebels', 'thrawn', 'Großadmiral Thrawn', 'GT', 29),
  ('star-wars', 'andor', 'cassian', 'Cassian Andor', 'CA', 30),
  ('star-wars', 'andor', 'mon-mothma', 'Mon Mothma', 'MM', 31),
  ('star-wars', 'andor', 'bix', 'Bix Caleen', 'BC', 32),
  ('star-wars', 'andor', 'syril', 'Syril Karn', 'SK', 33),
  ('star-wars', 'tales-of-the-underworld', 'ventress', 'Asajj Ventress', 'AV', 34),
  ('star-wars', 'tales-of-the-underworld', 'boba', 'Boba Fett', 'BF', 35),
  ('star-wars', 'the-mandalorian', 'din', 'Din Djarin', 'DD', 36),
  ('star-wars', 'the-mandalorian', 'grogu', 'Grogu', 'GR', 37),
  ('star-wars', 'the-mandalorian', 'greef', 'Greef Karga', 'GK', 38),
  ('star-wars', 'the-mandalorian', 'cara', 'Cara Dune', 'CD', 39),
  ('star-wars', 'the-mandalorian', 'gideon', 'Moff Gideon', 'MG', 40),
  ('star-wars', 'the-mandalorian', 'ig-11', 'IG-11', 'IG', 41),
  ('star-wars', 'the-mandalorian', 'kuiil', 'Kuiil', 'KU', 42),
  ('star-wars', 'book-of-boba-fett', 'boba', 'Boba Fett', 'BF', 43),
  ('star-wars', 'book-of-boba-fett', 'fennec', 'Fennec Shand', 'FS', 44),
  ('star-wars', 'book-of-boba-fett', 'din', 'Din Djarin', 'DD', 45),
  ('star-wars', 'book-of-boba-fett', 'cad-bane', 'Cad Bane', 'CB', 46),
  ('star-wars', 'skeleton-crew', 'wim', 'Wim', 'WI', 47),
  ('star-wars', 'skeleton-crew', 'fern', 'Fern', 'FE', 48),
  ('star-wars', 'skeleton-crew', 'jod', 'Jod Na Nawood', 'JN', 49),
  ('star-wars', 'skeleton-crew', 'sm-33', 'SM-33', 'SM', 50),
  ('star-wars', 'ahsoka', 'ahsoka-tano', 'Ahsoka Tano', 'AT', 51),
  ('star-wars', 'ahsoka', 'sabine', 'Sabine Wren', 'SW', 52),
  ('star-wars', 'ahsoka', 'din-ahsoka', 'Din Djarin', 'DD', 53),
  ('star-wars', 'ahsoka', 'thrawn-ahsoka', 'Großadmiral Thrawn', 'GT', 54),
  ('star-wars', 'maul-shadow-lord', 'maul', 'Darth Maul', 'DM', 55),
  ('star-wars', 'maul-shadow-lord', 'ochi', 'Ochi von Bestoon', 'OB', 56),
  ('star-wars', 'star-wars-resistance', 'kaz', 'Kazuda Xiono', 'KX', 57),
  ('star-wars', 'star-wars-resistance', 'poe', 'Poe Dameron', 'PD', 58),
  ('star-wars', 'star-wars-resistance', 'torra', 'Torra Doza', 'TD', 59);

INSERT INTO plot_points (universe_slug, id, work_slug, character_id, arc_id, at, text) VALUES
  ('star-wars', 'yja-0', 'young-jedi-adventures', 'kai-brightstar', 'yja-tempel', 1, 'Beginnt seine Ausbildung im Jedi-Tempel des Hochrepublik-Zeitalters.'),
  ('star-wars', 'yja-1', 'young-jedi-adventures', 'kai-brightstar', 'yja-freundschaft', 5, 'Lernt, dass wahre Jedi-Stärke aus Zusammenhalt statt Alleingang kommt.'),
  ('star-wars', 'yja-2', 'young-jedi-adventures', 'lys-solay', 'yja-freundschaft', 3, 'Hilft einem verängstigten Wesen, sich der Gruppe anzuschließen.'),
  ('star-wars', 'yja-3', 'young-jedi-adventures', 'nubs', 'yja-tempel', 2, 'Sorgt trotz fehlender Worte für den Zusammenhalt der jungen Padawane.'),
  ('star-wars', 'acolyte-0', 'the-acolyte', 'mae', 'acolyte-schwestern', 1, 'Beginnt eine Mordserie an den Jedi, die einst ihr Zuhause zerstörten.'),
  ('star-wars', 'acolyte-1', 'the-acolyte', 'osha', 'acolyte-schwestern', 3, 'Wird fälschlich der Verbrechen ihrer verschollen geglaubten Zwillingsschwester verdächtigt.'),
  ('star-wars', 'acolyte-2', 'the-acolyte', 'sol', 'acolyte-jedi', 6, 'Gesteht Osha, was auf Brendok wirklich geschah.'),
  ('star-wars', 'acolyte-3', 'the-acolyte', 'qimir', 'acolyte-schatten', 7, 'Enttarnt sich als heimlicher Sith-Lehrer im Hintergrund.'),
  ('star-wars', 'acolyte-4', 'the-acolyte', 'osha', 'acolyte-schatten', 8, 'Wendet sich nach dem Verlust ihrer Schwester der dunklen Seite zu.'),
  ('star-wars', 'episode-iv-0', 'episode-iv', 'luke', 'iv-held', 18, 'Findet Leias Hilferuf im Speicher von R2-D2.'),
  ('star-wars', 'episode-iv-1', 'episode-iv', 'luke', 'iv-held', 35, 'Verliert sein Zuhause und schließt sich Obi-Wan an.'),
  ('star-wars', 'episode-iv-2', 'episode-iv', 'luke', 'iv-rebellion', 48, 'Sucht mit Obi-Wan in Mos Eisley einen Piloten.'),
  ('star-wars', 'episode-iv-3', 'episode-iv', 'luke', 'iv-imperium', 75, 'Befreit Leia aus dem Zellenblock des Todessterns.'),
  ('star-wars', 'episode-iv-4', 'episode-iv', 'luke', 'iv-rebellion', 112, 'Fliegt den entscheidenden Angriff auf den Todesstern.'),
  ('star-wars', 'episode-iv-5', 'episode-iv', 'leia', 'iv-rebellion', 2, 'Versteckt die gestohlenen Pläne in R2-D2.'),
  ('star-wars', 'episode-iv-6', 'episode-iv', 'leia', 'iv-imperium', 40, 'Hält im Verhör stand – trotz Drohung gegen Alderaan.'),
  ('star-wars', 'episode-iv-7', 'episode-iv', 'leia', 'iv-held', 78, 'Übernimmt bei der eigenen Rettung das Kommando.'),
  ('star-wars', 'episode-iv-8', 'episode-iv', 'leia', 'iv-rebellion', 118, 'Ehrt die Helden nach der Schlacht von Yavin.'),
  ('star-wars', 'episode-iv-9', 'episode-iv', 'han', 'iv-rebellion', 50, 'Nimmt den Flug nach Alderaan gegen hohen Lohn an.'),
  ('star-wars', 'episode-iv-10', 'episode-iv', 'han', 'iv-imperium', 55, 'Entkommt mit dem Falken der imperialen Blockade.'),
  ('star-wars', 'episode-iv-11', 'episode-iv', 'han', 'iv-held', 108, 'Kehrt im letzten Moment zur Schlacht zurück.'),
  ('star-wars', 'episode-iv-12', 'episode-iv', 'vader', 'iv-imperium', 4, 'Entert das Rebellenschiff und sucht die Pläne.'),
  ('star-wars', 'episode-iv-13', 'episode-iv', 'vader', 'iv-held', 88, 'Trifft seinen alten Meister wieder.'),
  ('star-wars', 'episode-iv-14', 'episode-iv', 'vader', 'iv-imperium', 110, 'Verfolgt die Angreifer im Graben persönlich.'),
  ('star-wars', 'episode-iv-15', 'episode-iv', 'obi-wan', 'iv-held', 30, 'Erzählt Luke von dessen Vater und dem Lichtschwert.'),
  ('star-wars', 'episode-iv-16', 'episode-iv', 'obi-wan', 'iv-rebellion', 60, 'Schaltet den Traktorstrahl des Todessterns ab.'),
  ('star-wars', 'episode-iv-17', 'episode-iv', 'obi-wan', 'iv-held', 88, 'Stellt sich Vader im Duell.'),
  ('star-wars', 'episode-iv-18', 'episode-iv', 'r2-d2', 'iv-rebellion', 8, 'Flieht mit den Plänen auf den Wüstenplaneten.'),
  ('star-wars', 'episode-iv-19', 'episode-iv', 'r2-d2', 'iv-held', 22, 'Macht sich allein auf die Suche nach Obi-Wan.'),
  ('star-wars', 'episode-iv-20', 'episode-iv', 'r2-d2', 'iv-rebellion', 105, 'Fliegt als Astromech hinter Luke in die Schlacht.'),
  ('star-wars', 'episode-iv-21', 'episode-iv', 'c-3po', 'iv-rebellion', 10, 'Landet mit R2-D2 in einer Rettungskapsel auf Tatooine.'),
  ('star-wars', 'episode-iv-22', 'episode-iv', 'c-3po', 'iv-imperium', 80, 'Hält im Kontrollraum die Stellung.'),
  ('star-wars', 'episode-iv-23', 'episode-iv', 'tarkin', 'iv-imperium', 38, 'Demonstriert die Macht der Station an Alderaan.'),
  ('star-wars', 'episode-iv-24', 'episode-iv', 'tarkin', 'iv-imperium', 114, 'Lehnt die Evakuierung der Station ab.'),
  ('star-wars', 'episode-iv-25', 'episode-iv', 'chewbacca', 'iv-rebellion', 50, 'Fliegt mit Han den Millennium Falken.'),
  ('star-wars', 'episode-iv-26', 'episode-iv', 'chewbacca', 'iv-imperium', 70, 'Spielt den Gefangenen, um in den Zellenblock zu kommen.'),
  ('star-wars', 'batch-0', 'bad-batch', 'hunter', 'batch-batch', 1, 'Übernimmt nach Order 66 das Kommando über die desorientierte Truppe.'),
  ('star-wars', 'batch-1', 'bad-batch', 'hunter', 'batch-imperium', 3, 'Lehnt die Umrüstung auf Kontroll-Chips ab und flieht mit dem Team.'),
  ('star-wars', 'batch-2', 'bad-batch', 'omega', 'batch-batch', 1, 'Schließt sich der Truppe als heimliches Klon-Mädchen an.'),
  ('star-wars', 'batch-3', 'bad-batch', 'omega', 'batch-rat', 8, 'Wird von Nala Se als genetisch besonders wertvoll identifiziert.'),
  ('star-wars', 'batch-4', 'bad-batch', 'crosshair', 'batch-imperium', 1, 'Bleibt dem Imperium treu und wird zum Gegenspieler seines eigenen Teams.'),
  ('star-wars', 'batch-5', 'bad-batch', 'crosshair', 'batch-imperium', 16, 'Bricht endgültig mit dem Imperium, nachdem er selbst zur Wegwerfware wird.'),
  ('star-wars', 'batch-6', 'bad-batch', 'nala-se', 'batch-rat', 3, 'Versucht, die Klonforschung vor imperialem Zugriff zu schützen.'),
  ('star-wars', 'tote-0', 'tales-of-the-empire', 'morgan-elsbeth', 'tote-inquisitorin', 1, 'Verliert ihre Heimat Dathomir an die Klonkriege und schwört Rache.'),
  ('star-wars', 'tote-1', 'tales-of-the-empire', 'morgan-elsbeth', 'tote-inquisitorin', 3, 'Steigt zur Handlangerin Thrawns und zur Magistratin von Corvus auf.'),
  ('star-wars', 'tote-2', 'tales-of-the-empire', 'barriss', 'tote-dathomir', 4, 'Verlässt nach ihrem Verrat den Jedi-Orden und sucht in der Dunkelheit neuen Sinn.'),
  ('star-wars', 'kenobi-0', 'obi-wan-kenobi', 'obi-wan', 'kenobi-obi-wan', 1, 'Lebt zurückgezogen auf Tatooine und wacht heimlich über den jungen Luke.'),
  ('star-wars', 'kenobi-1', 'obi-wan-kenobi', 'obi-wan', 'kenobi-obi-wan', 2, 'Reist nach Daiyu, um die entführte Leia zu retten.'),
  ('star-wars', 'kenobi-2', 'obi-wan-kenobi', 'obi-wan', 'kenobi-vader', 4, 'Stellt sich Vader zum ersten Mal seit Mustafar in einem verheerenden Duell.'),
  ('star-wars', 'kenobi-3', 'obi-wan-kenobi', 'obi-wan', 'kenobi-anakin', 6, 'Erkennt, dass in Vader nichts vom einstigen Anakin übrig ist – und lässt los.'),
  ('star-wars', 'kenobi-4', 'obi-wan-kenobi', 'leia-organa', 'kenobi-obi-wan', 1, 'Wird von Kopfgeldjägern der Dritten Schwester entführt.'),
  ('star-wars', 'kenobi-5', 'obi-wan-kenobi', 'leia-organa', 'kenobi-obi-wan', 3, 'Beginnt, dem widerwilligen Obi-Wan zu vertrauen.'),
  ('star-wars', 'kenobi-6', 'obi-wan-kenobi', 'vader', 'kenobi-anakin', 3, 'Lässt Reva wissen, dass er von Obi-Wans Überleben erfahren hat.'),
  ('star-wars', 'kenobi-7', 'obi-wan-kenobi', 'vader', 'kenobi-vader', 4, 'Setzt ein Dorf in Brand, um Obi-Wan aus der Deckung zu locken.'),
  ('star-wars', 'kenobi-8', 'obi-wan-kenobi', 'reva', 'kenobi-vader', 5, 'Enthüllt ihre wahre Absicht: Rache an Vader statt Loyalität.'),
  ('star-wars', 'kenobi-9', 'obi-wan-kenobi', 'reva', 'kenobi-vader', 6, 'Verschont den jungen Luke auf Tatooine und lässt von der Rache ab.'),
  ('star-wars', 'rebels-0', 'star-wars-rebels', 'ezra', 'rebels-ghost', 1, 'Wird von der Crew der Ghost aus dem Leben als Straßendieb auf Lothal geholt.'),
  ('star-wars', 'rebels-1', 'star-wars-rebels', 'ezra', 'rebels-erwachen', 15, 'Opfert sich, um Thrawn ins unbekannte Weltall zu verbannen.'),
  ('star-wars', 'rebels-2', 'star-wars-rebels', 'kanan', 'rebels-ghost', 1, 'Bildet Ezra heimlich als Jedi aus, ohne Orden oder Tempel.'),
  ('star-wars', 'rebels-3', 'star-wars-rebels', 'kanan', 'rebels-imperium', 12, 'Verliert im Kampf gegen die Inquisitoren sein Augenlicht.'),
  ('star-wars', 'rebels-4', 'star-wars-rebels', 'hera', 'rebels-erwachen', 5, 'Vereint verstreute Widerstandszellen zur organisierten Rebellion.'),
  ('star-wars', 'rebels-5', 'star-wars-rebels', 'thrawn', 'rebels-imperium', 10, 'Analysiert die Kunst und Taktik der Rebellen, um sie gezielt zu zerschlagen.'),
  ('star-wars', 'andor-0', 'andor', 'cassian', 'andor-cassian', 1, 'Sucht auf Ferrix Antworten zum Verschwinden seiner Schwester – und tötet zwei Corp-Wachen in Notwehr.'),
  ('star-wars', 'andor-1', 'andor', 'cassian', 'andor-rebellion', 3, 'Wird von Luthen Rael angeworben, nachdem er der ISB nur knapp entkommt.'),
  ('star-wars', 'andor-2', 'andor', 'cassian', 'andor-imperium', 8, 'Wird ohne fairen Prozess zu sechs Jahren Zwangsarbeit auf Narkina 5 verurteilt.'),
  ('star-wars', 'andor-3', 'andor', 'cassian', 'andor-rebellion', 10, 'Organisiert den Ausbruch aus dem Gefängniskomplex.'),
  ('star-wars', 'andor-4', 'andor', 'cassian', 'andor-cassian', 12, 'Kehrt nach Ferrix zurück und übernimmt bei Maarvas Beerdigung offen die Rolle des Rebellen.'),
  ('star-wars', 'andor-5', 'andor', 'mon-mothma', 'andor-rebellion', 4, 'Schleust unter dem Deckmantel der Wohltätigkeit Gelder zur Finanzierung der Rebellion.'),
  ('star-wars', 'andor-6', 'andor', 'mon-mothma', 'andor-imperium', 9, 'Manövriert sich im Senat gegen wachsendes Misstrauen ihres Umfelds und der ISB.'),
  ('star-wars', 'andor-7', 'andor', 'bix', 'andor-cassian', 2, 'Verschafft Cassian einen riskanten Deal mit einem Schmuggler.'),
  ('star-wars', 'andor-8', 'andor', 'bix', 'andor-imperium', 11, 'Wird von der ISB verhört und schwer gefoltert.'),
  ('star-wars', 'andor-9', 'andor', 'syril', 'andor-imperium', 1, 'Verfolgt eigenmächtig die Ermittlungen zum Doppelmord auf Ferrix, gegen den Willen seiner Vorgesetzten.'),
  ('star-wars', 'andor-10', 'andor', 'syril', 'andor-imperium', 9, 'Wird von der ISB rekrutiert, um Cassian auf Chandrila aufzuspüren.'),
  ('star-wars', 'totu-0', 'tales-of-the-underworld', 'ventress', 'totu-unterwelt', 1, 'Arbeitet als Kopfgeldjägerin an der Seite von Boba Fett auf einem riskanten Auftrag.'),
  ('star-wars', 'totu-1', 'tales-of-the-underworld', 'boba', 'totu-unterwelt', 3, 'Bekräftigt vor Ventress seinen Ruf als gnadenloser Kopfgeldjäger.'),
  ('star-wars', 'the-mandalorian-0', 'the-mandalorian', 'din', 'm-gilde', 1, 'Nimmt einen ungewöhnlichen Auftrag des Klienten an.'),
  ('star-wars', 'the-mandalorian-1', 'the-mandalorian', 'din', 'm-kind', 1, 'Findet sein Ziel – und es ist ein Kind.'),
  ('star-wars', 'the-mandalorian-2', 'the-mandalorian', 'din', 'm-gilde', 3, 'Liefert ab, bereut es und holt das Kind zurück.'),
  ('star-wars', 'the-mandalorian-3', 'the-mandalorian', 'din', 'm-kind', 4, 'Sucht auf Sorgan ein Versteck für das Kind.'),
  ('star-wars', 'the-mandalorian-4', 'the-mandalorian', 'din', 'm-gideon', 7, 'Kehrt nach Nevarro zurück, um den Klienten zu stellen.'),
  ('star-wars', 'the-mandalorian-5', 'the-mandalorian', 'din', 'm-kind', 8, 'Nimmt den Auftrag an, das Kind zu seinesgleichen zu bringen.'),
  ('star-wars', 'the-mandalorian-6', 'the-mandalorian', 'grogu', 'm-kind', 1, 'Wird im Lager der Nikto entdeckt.'),
  ('star-wars', 'the-mandalorian-7', 'the-mandalorian', 'grogu', 'm-kind', 2, 'Hebt mit der Macht einen Mudhorn an.'),
  ('star-wars', 'the-mandalorian-8', 'the-mandalorian', 'grogu', 'm-gideon', 7, 'Wird von Sturmtruppen entführt.'),
  ('star-wars', 'the-mandalorian-9', 'the-mandalorian', 'greef', 'm-gilde', 1, 'Vermittelt Din den Auftrag.'),
  ('star-wars', 'the-mandalorian-10', 'the-mandalorian', 'greef', 'm-gilde', 3, 'Führt die Gilde gegen Din an.'),
  ('star-wars', 'the-mandalorian-11', 'the-mandalorian', 'greef', 'm-gideon', 7, 'Bietet Din einen Deal an – mit Hintergedanken.'),
  ('star-wars', 'the-mandalorian-12', 'the-mandalorian', 'cara', 'm-kind', 4, 'Trifft Din auf Sorgan im Zweikampf.'),
  ('star-wars', 'the-mandalorian-13', 'the-mandalorian', 'cara', 'm-gideon', 7, 'Schließt sich dem Plan für Nevarro an.'),
  ('star-wars', 'the-mandalorian-14', 'the-mandalorian', 'gideon', 'm-gideon', 7, 'Umstellt die Cantina auf Nevarro.'),
  ('star-wars', 'the-mandalorian-15', 'the-mandalorian', 'gideon', 'm-gideon', 8, 'Taucht mit dem Dunkelschwert auf.'),
  ('star-wars', 'the-mandalorian-16', 'the-mandalorian', 'ig-11', 'm-gilde', 1, 'Wetteifert mit Din um dasselbe Ziel.'),
  ('star-wars', 'the-mandalorian-17', 'the-mandalorian', 'ig-11', 'm-kind', 8, 'Beschützt das Kind – umprogrammiert.'),
  ('star-wars', 'the-mandalorian-18', 'the-mandalorian', 'kuiil', 'm-kind', 1, 'Hilft Din, das Lager zu erreichen.'),
  ('star-wars', 'the-mandalorian-19', 'the-mandalorian', 'kuiil', 'm-kind', 2, 'Repariert das zerlegte Schiff.'),
  ('star-wars', 'the-mandalorian-20', 'the-mandalorian', 'kuiil', 'm-kind', 7, 'Bringt das Kind in Sicherheit.'),
  ('star-wars', 'boba-0', 'book-of-boba-fett', 'boba', 'boba-vergangenheit', 2, 'Wird von Tuskenräubern gefangen genommen und lernt ihre Lebensweise.'),
  ('star-wars', 'boba-1', 'book-of-boba-fett', 'boba', 'boba-thron', 1, 'Übernimmt Jabbas altes Territorium auf Tatooine.'),
  ('star-wars', 'boba-2', 'book-of-boba-fett', 'boba', 'boba-thron', 5, 'Muss sich gegen die Übernahmeversuche des Pyke-Syndikats behaupten.'),
  ('star-wars', 'boba-3', 'book-of-boba-fett', 'fennec', 'boba-thron', 1, 'Wird Bobas rechte Hand und Sicherheitschefin.'),
  ('star-wars', 'boba-4', 'book-of-boba-fett', 'fennec', 'boba-thron', 5, 'Verhandelt mit den Straßenbanden von Mos Espa um Unterstützung.'),
  ('star-wars', 'boba-5', 'book-of-boba-fett', 'din', 'boba-tatooine', 6, 'Hilft Boba im entscheidenden Kampf gegen die Pykes.'),
  ('star-wars', 'boba-6', 'book-of-boba-fett', 'cad-bane', 'boba-thron', 6, 'Fordert Boba im Duell heraus, im Auftrag der Pykes.'),
  ('star-wars', 'sc-0', 'skeleton-crew', 'wim', 'sc-kinder', 1, 'Findet mit Freunden ein vergrabenes altes Schiff und startet versehentlich in den Hyperraum.'),
  ('star-wars', 'sc-1', 'skeleton-crew', 'wim', 'sc-galaxis', 8, 'Kehrt mit neuem Blick auf seine ruhige Heimatwelt zurück.'),
  ('star-wars', 'sc-2', 'skeleton-crew', 'fern', 'sc-kinder', 2, 'Übernimmt in der Gruppe die Führungsrolle, als Erwachsene fehlen.'),
  ('star-wars', 'sc-3', 'skeleton-crew', 'jod', 'sc-jod', 3, 'Gibt sich den Kindern gegenüber als Jedi aus, um ihr Vertrauen zu gewinnen.'),
  ('star-wars', 'sc-4', 'skeleton-crew', 'jod', 'sc-jod', 7, 'Wird als Pirat und Betrüger entlarvt.'),
  ('star-wars', 'sc-5', 'skeleton-crew', 'sm-33', 'sc-galaxis', 1, 'Erkennt die Kinder fälschlich als seine ''Captains'' an.'),
  ('star-wars', 'ahsoka-0', 'ahsoka', 'ahsoka-tano', 'ahsoka-ahsoka', 1, 'Folgt einer alten Karte, die zum verschollenen Großadmiral Thrawn führen soll.'),
  ('star-wars', 'ahsoka-1', 'ahsoka', 'ahsoka-tano', 'ahsoka-empire', 7, 'Stellt sich Thrawn im fernen Weltall zum entscheidenden Duell.'),
  ('star-wars', 'ahsoka-2', 'ahsoka', 'sabine', 'ahsoka-ahsoka', 2, 'Wird von Ahsoka in den Wegen der Macht unterrichtet, gegen deren eigene Zweifel.'),
  ('star-wars', 'ahsoka-3', 'ahsoka', 'sabine', 'ahsoka-din-djarin', 5, 'Reist eigenmächtig ins Unbekannte Weltall, um Ezra zu retten.'),
  ('star-wars', 'ahsoka-4', 'ahsoka', 'din-ahsoka', 'ahsoka-din-djarin', 4, 'Verrät Ahsoka Sabines Aufenthaltsort – aus Verpflichtung, nicht Überzeugung.'),
  ('star-wars', 'ahsoka-5', 'ahsoka', 'thrawn-ahsoka', 'ahsoka-empire', 7, 'Kehrt mit einer neuen Flotte aus dem Exil zurück.'),
  ('star-wars', 'maul-0', 'maul-shadow-lord', 'maul', 'maul-schatten', 1, 'Baut im Verborgenen ein neues Verbrechensnetzwerk nach dem Fall seines alten Syndikats auf.'),
  ('star-wars', 'maul-1', 'maul-shadow-lord', 'maul', 'maul-rache', 5, 'Verfolgt weiter seine Obsession, die Skywalker-Blutlinie auszulöschen.'),
  ('star-wars', 'maul-2', 'maul-shadow-lord', 'ochi', 'maul-schatten', 3, 'Bietet Maul seine Dienste als Assassine an.'),
  ('star-wars', 'resistance-0', 'star-wars-resistance', 'kaz', 'resistance-kaz', 1, 'Wird als verdeckter Spion des Widerstands auf die Ölplattform Colossus geschickt.'),
  ('star-wars', 'resistance-1', 'star-wars-resistance', 'poe', 'resistance-kaz', 1, 'Rekrutiert Kaz für die geheime Aufklärungsmission gegen die Erste Ordnung.'),
  ('star-wars', 'resistance-2', 'star-wars-resistance', 'torra', 'resistance-erste-ordnung', 18, 'Verteidigt Colossus gegen den offenen Angriff der Ersten Ordnung.'),
  ('star-wars', 'resistance-3', 'star-wars-resistance', 'kaz', 'resistance-erste-ordnung', 21, 'Schließt sich offen dem Widerstand gegen die Erste Ordnung an.');

-- Fate

INSERT INTO universes (slug, name, sort_order) VALUES
  ('fate', 'Fate', 1);

INSERT INTO sagas (universe_slug, id, name, tone, sort_order) VALUES
  ('fate', 'saga-stay-night', 'Fate/stay night Routen-Ära', 'arc-1', 0),
  ('fate', 'saga-zero', 'Vierter Heiliger Gralkrieg (Fate/Zero)', 'arc-2', 1),
  ('fate', 'saga-prototype', 'Fate/Prototype Universum', 'neutral', 2),
  ('fate', 'saga-kaleid-parallel', 'Kaleid-Parallelwelt (Prisma Illya)', 'arc-1', 3),
  ('fate', 'saga-apocrypha', 'Großer Gralkrieg (Apocrypha)', 'neutral', 4),
  ('fate', 'saga-grand-order-babylonia', 'Grand Order: Singularitäten', 'arc-3', 5),
  ('fate', 'saga-grand-order-lostbelt', 'Grand Order / Cosmos in the Lostbelt', 'arc-3', 6),
  ('fate', 'saga-fifth-war', 'Nach dem fünften Gralkrieg', 'neutral', 7);

INSERT INTO works (universe_slug, slug, title, short, kind, released, chronology, lore_date, saga_id, required, unit, range_start, range_end, now_playing, sort_order) VALUES
  ('fate', 'fate-stay-night-2006', 'Fate/stay night', 'stay night', 'serie', '2006-01-07', 30, '2004', 'saga-stay-night', 1, 'Folge', 1, 24, NULL, 0),
  ('fate', 'fate-zero', 'Fate/Zero', 'Zero', 'serie', '2011-10-01', 20, '1994', 'saga-zero', 1, 'Folge', 1, 25, NULL, 1),
  ('fate', 'fate-prototype', 'Fate/Prototype', 'Prototype', 'film', '2011-12-31', 10, '2003', 'saga-prototype', 0, 'Min.', 0, 12, NULL, 2),
  ('fate', 'fate-kaleid-liner-prisma-illya', 'Fate/kaleid liner PRISMA☆ILLYA', 'Prisma Illya', 'serie', '2013-07-13', 90, '2014', 'saga-kaleid-parallel', 1, 'Folge', 1, 10, NULL, 3),
  ('fate', 'fate-stay-night-unlimited-blade-works', 'Fate/stay night: Unlimited Blade Works', 'UBW', 'serie', '2014-10-04', 40, '2004', 'saga-stay-night', 1, 'Folge', 1, 25, NULL, 4),
  ('fate', 'fate-apocrypha', 'Fate/Apocrypha', 'Apocrypha', 'serie', '2017-07-02', 110, '2015', 'saga-apocrypha', 1, 'Folge', 1, 25, NULL, 5),
  ('fate', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'Fate/kaleid liner PRISMA ILLYA: Oath Under Snow', 'Prisma Movie 1', 'film', '2017-08-26', 100, '2015', 'saga-kaleid-parallel', 0, 'Min.', 0, 90, NULL, 6),
  ('fate', 'fate-heavens-feel-1-presage-flower', 'Fate/stay night: Heaven''s Feel I. presage flower', 'Heaven''s Feel I', 'film', '2017-10-14', 50, '2004', 'saga-stay-night', 1, 'Min.', 0, 120, NULL, 7),
  ('fate', 'fate-grand-order-moonlight-lostroom', 'Fate/Grand Order -MOONLIGHT/LOSTROOM-', 'Lostroom OVA', 'film', '2017-12-31', 120, '2016', 'saga-grand-order-lostbelt', 1, 'Min.', 0, 32, NULL, 8),
  ('fate', 'todays-menu-for-the-emiya-family', 'Today''s Menu for the Emiya Family', 'Emiya Gohan', 'serie', '2018-01-25', 80, '2005', 'saga-fifth-war', 0, 'Folge', 1, 13, NULL, 9),
  ('fate', 'fate-heavens-feel-2-lost-butterfly', 'Fate/stay night: Heaven''s Feel II. lost butterfly', 'Heaven''s Feel II', 'film', '2019-01-12', 60, '2004', 'saga-stay-night', 1, 'Min.', 0, 117, NULL, 10),
  ('fate', 'fate-grand-order-babylonia', 'Fate/Grand Order -Absolute Demonic Front: Babylonia-', 'Babylonia', 'serie', '2019-10-05', 140, '2016', 'saga-grand-order-babylonia', 1, 'Folge', 1, 21, NULL, 11),
  ('fate', 'fate-heavens-feel-3-spring-song', 'Fate/stay night: Heaven''s Feel III. spring song', 'Heaven''s Feel III', 'film', '2020-08-15', 70, '2004', 'saga-stay-night', 1, 'Min.', 0, 122, NULL, 12),
  ('fate', 'fate-grand-order-camelot', 'Fate/Grand Order THE MOVIE: Divine Realm of the Round Table -Camelot- Wandering; Agateram', 'Camelot', 'film', '2020-12-05', 130, '2016', 'saga-grand-order-babylonia', 0, 'Min.', 0, 89, NULL, 13);

INSERT INTO arcs (universe_slug, id, work_slug, name, tone, sort_order) VALUES
  ('fate', 'stay-night-fate-route', 'fate-stay-night-2006', 'Der Fate-Pfad: Shirous erster Gralkrieg', 'arc-1', 0),
  ('fate', 'zero-fourth-war', 'fate-zero', 'Der Vierte Heilige Gralkrieg', 'arc-2', 1),
  ('fate', 'proto-tokyo-1991', 'fate-prototype', 'Erster Tokio Gralkrieg (1991)', 'neutral', 2),
  ('fate', 'prisma-illya-transformation', 'fate-kaleid-liner-prisma-illya', 'Illyas Verwandlung zur Kaleidscope-Kriegerin', 'arc-1', 3),
  ('fate', 'ubw-route', 'fate-stay-night-unlimited-blade-works', 'Der UBW-Pfad: Rins Route und Archer', 'arc-1', 4),
  ('fate', 'apocrypha-great-war', 'fate-apocrypha', 'Schwarze und Rote Fraktion im Großen Gralkrieg', 'neutral', 5),
  ('fate', 'prisma-oath-shirou', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'Shirous Gralkrieg in der sterbenden Welt', 'arc-1', 6),
  ('fate', 'hf-1-shadow', 'fate-heavens-feel-1-presage-flower', 'Sakuras Schatten erwacht', 'arc-1', 7),
  ('fate', 'fgo-lostbelt-prologue', 'fate-grand-order-moonlight-lostroom', 'Schatten der ausgelöschten Zukunft', 'arc-3', 8),
  ('fate', 'gohan-alltag', 'todays-menu-for-the-emiya-family', 'Emiya-Haushalt Kochalltag', 'neutral', 9),
  ('fate', 'hf-2-corruption', 'fate-heavens-feel-2-lost-butterfly', 'Der Fall in die Verderbnis', 'arc-1', 10),
  ('fate', 'babylonia-singularity', 'fate-grand-order-babylonia', 'Die erste Singularität: Uruk', 'arc-3', 11),
  ('fate', 'hf-3-finale', 'fate-heavens-feel-3-spring-song', 'Das letzte Gefecht um Sakura', 'arc-1', 12),
  ('fate', 'camelot-round-table', 'fate-grand-order-camelot', 'Der Runde Tisch von Camelot', 'arc-3', 13);

INSERT INTO characters (universe_slug, work_slug, id, name, initials, sort_order) VALUES
  ('fate', 'fate-stay-night-2006', 'shirou-emiya-fsn', 'Shirou Emiya', 'SE', 0),
  ('fate', 'fate-zero', 'kiritsugu-emiya', 'Kiritsugu Emiya', 'KE', 1),
  ('fate', 'fate-prototype', 'arthur-pendragon-proto', 'Saber (Arthur Pendragon Prototype)', 'AP', 2),
  ('fate', 'fate-kaleid-liner-prisma-illya', 'illya-kaleid', 'Illyasviel von Einzbern', 'IE', 3),
  ('fate', 'fate-stay-night-unlimited-blade-works', 'rin-tohsaka', 'Rin Tohsaka', 'RT', 4),
  ('fate', 'fate-apocrypha', 'sieg-apocrypha', 'Sieg', 'SI', 5),
  ('fate', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'miyu-edelfelt-oath', 'Miyu Edelfelt', 'ME', 6),
  ('fate', 'fate-heavens-feel-1-presage-flower', 'sakura-matou-hf', 'Sakura Matou', 'SM', 7),
  ('fate', 'fate-grand-order-moonlight-lostroom', 'ritsuka-fujimaru', 'Ritsuka Fujimaru', 'RF', 8),
  ('fate', 'todays-menu-for-the-emiya-family', 'shirou-emiya-gohan', 'Shirou Emiya', 'SE', 9),
  ('fate', 'fate-heavens-feel-2-lost-butterfly', 'shirou-emiya-hf', 'Shirou Emiya', 'SE', 10),
  ('fate', 'fate-grand-order-babylonia', 'mash-kyrielight', 'Mash Kyrielight', 'MK', 11),
  ('fate', 'fate-heavens-feel-3-spring-song', 'illyasviel-hf', 'Illyasviel von Einzbern', 'IE', 12),
  ('fate', 'fate-grand-order-camelot', 'lancelot-camelot', 'Lancelot', 'LA', 13);

INSERT INTO plot_points (universe_slug, id, work_slug, character_id, arc_id, at, text) VALUES
  ('fate', 'pp-stay-night-1', 'fate-stay-night-2006', 'shirou-emiya-fsn', 'stay-night-fate-route', 1, 'Shirou Emiya wird ungewollt in den fünften Heiligen Gralkrieg gezogen und beschwört Saber.'),
  ('fate', 'pp-zero-1', 'fate-zero', 'kiritsugu-emiya', 'zero-fourth-war', 1, 'Kiritsugu Emiya kämpft als Meister von Saber im vierten Heiligen Gralkrieg um den Gral.'),
  ('fate', 'pp-proto-1', 'fate-prototype', 'arthur-pendragon-proto', 'proto-tokyo-1991', 1, 'Arthur Pendragon kämpft im Tokio-Gralkrieg von 1991 an der Seite von Manaka Sajyou.'),
  ('fate', 'pp-prisma-illya-1', 'fate-kaleid-liner-prisma-illya', 'illya-kaleid', 'prisma-illya-transformation', 1, 'Illyasviel wird von Magical Ruby zur Kaleidscope-Magical-Girl gemacht und muss Klassenkarten sammeln.'),
  ('fate', 'pp-ubw-1', 'fate-stay-night-unlimited-blade-works', 'rin-tohsaka', 'ubw-route', 1, 'Rin Tohsaka führt Shirou durch ihre Route des Gralkriegs und stellt ihn Archer gegenüber.'),
  ('fate', 'pp-apocrypha-1', 'fate-apocrypha', 'sieg-apocrypha', 'apocrypha-great-war', 1, 'Der Homunculus Sieg entkommt als Ersatz-Servant der Roten Fraktion und sucht seinen eigenen Weg.'),
  ('fate', 'pp-oath-1', 'fate-kaleid-liner-prisma-illya-oath-under-snow', 'miyu-edelfelt-oath', 'prisma-oath-shirou', 45, 'Shirou Emiya gewinnt den Ainsworth-Gralkrieg in einer einzigen Nacht, um Miyu in eine andere Welt zu retten.'),
  ('fate', 'pp-hf1-1', 'fate-heavens-feel-1-presage-flower', 'sakura-matou-hf', 'hf-1-shadow', 10, 'Sakura Matous dunkles Geheimnis beginnt Shirous Welt zu erschüttern.'),
  ('fate', 'pp-lostroom-1', 'fate-grand-order-moonlight-lostroom', 'ritsuka-fujimaru', 'fgo-lostbelt-prologue', 5, 'Ritsuka Fujimaru und Mash Kyrielight entdecken zu Weihnachten Chaldeas verborgenen ''Lost Room''.'),
  ('fate', 'pp-gohan-1', 'todays-menu-for-the-emiya-family', 'shirou-emiya-gohan', 'gohan-alltag', 1, 'Shirou kocht ein saisonales Gericht und bringt Rin, Sakura und Taiga an einen gemeinsamen Tisch.'),
  ('fate', 'pp-hf2-1', 'fate-heavens-feel-2-lost-butterfly', 'shirou-emiya-hf', 'hf-2-corruption', 60, 'Shirou nimmt Angra Mainyus Makel in sich auf, um Sakura zu retten.'),
  ('fate', 'pp-babylonia-1', 'fate-grand-order-babylonia', 'mash-kyrielight', 'babylonia-singularity', 3, 'Mash Kyrielight begleitet den Meister ins alte Uruk, die erste verlorene Singularität.'),
  ('fate', 'pp-hf3-1', 'fate-heavens-feel-3-spring-song', 'illyasviel-hf', 'hf-3-finale', 90, 'Illyasviel von Einzbern opfert sich im finalen Kampf um Sakuras Erlösung.'),
  ('fate', 'pp-camelot-1', 'fate-grand-order-camelot', 'lancelot-camelot', 'camelot-round-table', 30, 'Lancelot verteidigt als Wahnsinniger Ritter die Tafelrunde gegen Chaldeas Meister.');
